include:
  - project: 'dev_tls/giza/templates'
    ref: production
    file: 'rollback.gitlab-ci.yml'

image: ${DOCKER_REGISTRY_ADDRESS}/openshift3/ose-cli:${DOCKER_TAG_OSE_CLI}

default:
  tags:
    - tlsdev-aws

variables:
  APPLICATION_NAME: payment-api
  ENV: "SANDBOX"
  APP_ENV: "test"
  DATABASE: $DATABASE
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

stages:
  - analyze
  - build
  - deploy
  - expose
  - rollback

sonarcloud-check:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop

prepare-instance:
  stage: build
  image: ${DOCKER_REGISTRY_ADDRESS}/tlscontact/composer:${DOCKER_TAG_COMPOSER}
  script:
    - composer install -o
  after_script:
    - rm -rf composer.*
  artifacts:
    paths:
      - ./
    expire_in: 1 hour
  environment:
    name: $ENV

.deploy-instance:
  variables:
    MEMORY_REQUEST: 100Mi
    MEMORY_LIMIT: 256Mi
  stage: deploy
  only:
    variables:
      - $PROJECT
  before_script:
    - echo $MASTER_PUBLIC_URL
    - oc login --token=$GITLAB_SA_TOKEN --insecure-skip-tls-verify=true $MASTER_PUBLIC_URL
  script:
    - oc project "$PROJECT" 2> /dev/null || oc new-project "$PROJECT"
    - export PAYMENT_SERVICE_URL=`oc get route payment -o jsonpath='{.spec.host}'`
    - oc process -f ./openshift/payment-api-template.yaml APPLICATION_NAME=$APPLICATION_NAME PROJECT=$INSTANCE
      NAMESPACE=$PROJECT
      APP_ENV=$APP_ENV
      OPENSHIFT_ENV=$ENV
      ROUTE_IP_WHITE_LIST="$ROUTE_IP_WHITE_LIST"
      POSTGRES_DB_HOST="pgbouncer"
      POSTGRES_SECRET_NAME="${PROJECT}-pgcluster-common-secret"
      POSTGRES_ADMIN_SECRET_NAME="${PROJECT}-pgsql-master"
      POSTGRES_PAYMENT_DB_DATABASE="payment-$DATABASE"
      AWS_ACCOUNT_S3="tlspay-s3-account"
      PAYMENT_SERVICE_DOMAIN="https://$PAYMENT_SERVICE_URL"
      TLSCONTACT_API="$TLSCONTACT_API"
      KBANK_THBKK2BE_SANDBOX_API_KEY=$KBANK_THBKK2BE_SANDBOX_API_KEY
      KBANK_THBKK2BE_SANDBOX_SECRET=$KBANK_THBKK2BE_SANDBOX_SECRET
      KBANK_THBKK2BE_SANDBOX_MID=$KBANK_THBKK2BE_SANDBOX_MID
      KBANK_THBKK2BE_API_KEY=$KBANK_THBKK2BE_API_KEY
      KBANK_THBKK2BE_SECRET=$KBANK_THBKK2BE_SECRET
      KBANK_THBKK2BE_MID=$KBANK_THBKK2BE_MID
      ENVPAY_CMI_BEmaAll2be_SANDBOX_MERCHANT_ID=$ENVPAY_CMI_BEmaAll2be_SANDBOX_MERCHANT_ID
      ENVPAY_CMI_BEmaAll2be_SANDBOX_STOREKEY=$ENVPAY_CMI_BEmaAll2be_SANDBOX_STOREKEY
      ENVPAY_CMI_BEmaAll2be_MERCHANT_ID=$ENVPAY_CMI_BEmaAll2be_MERCHANT_ID
      ENVPAY_CMI_BEmaAll2be_STOREKEY=$ENVPAY_CMI_BEmaAll2be_STOREKEY
      ENVPAY_TINGG_COMMON_SANDBOX_ACCOUNT_NUMBER=$ENVPAY_TINGG_COMMON_SANDBOX_ACCOUNT_NUMBER
      ENVPAY_TINGG_COMMON_SANDBOX_SERVICE_CODE=$ENVPAY_TINGG_COMMON_SANDBOX_SERVICE_CODE
      ENVPAY_TINGG_COMMON_SANDBOX_IVKEY=$ENVPAY_TINGG_COMMON_SANDBOX_IVKEY
      ENVPAY_TINGG_COMMON_SANDBOX_SECRET_KEY=$ENVPAY_TINGG_COMMON_SANDBOX_SECRET_KEY
      ENVPAY_TINGG_COMMON_SANDBOX_ACCESS_KEY="$ENVPAY_TINGG_COMMON_SANDBOX_ACCESS_KEY"
      ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_ID=$ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_ID
      ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_SECRET=$ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_SECRET
      ENVPAY_TINGG_COMMON_SANDBOX_OAUTH_HOST=$ENVPAY_TINGG_COMMON_SANDBOX_OAUTH_HOST
      ENVPAY_TINGG_COMMON_SANDBOX_QUERY_STATUS_HOST=$ENVPAY_TINGG_COMMON_SANDBOX_QUERY_STATUS_HOST
      PAYGATE_ZAALL2BE_ENCRYPTION_SANDBOX_KEY=$PAYGATE_ZAALL2BE_ENCRYPTION_SANDBOX_KEY
      PAYGATE_ZAALL2BE_SANDBOX_ID=$PAYGATE_ZAALL2BE_SANDBOX_ID
      PAYGATE_ZAALL2BE_ENCRYPTION_KEY=$PAYGATE_ZAALL2BE_ENCRYPTION_KEY
      PAYGATE_ZAALL2BE_ID=$PAYGATE_ZAALL2BE_ID
      PAYGATE_ZAALL2BE_SELLER_EMAIL=$PAYGATE_ZAALL2BE_SELLER_EMAIL
      FAW_COMMON_SANDBOX_MERCHANT_ID=$FAW_COMMON_SANDBOX_MERCHANT_ID
      FAW_COMMON_SANDBOX_SECRET_KEY=$FAW_COMMON_SANDBOX_SECRET_KEY
      ENVPAY_GLO_COMMON_SANDBOX_MERCHANT_ID=$ENVPAY_GLO_COMMON_SANDBOX_MERCHANT_ID
      ENVPAY_GLO_COMMON_SANDBOX_SECRET=$ENVPAY_GLO_COMMON_SANDBOX_SECRET
      ENVPAY_GLO_BEgbALL2be_ACCOUNT=$ENVPAY_GLO_BEgbALL2be_ACCOUNT
      ENVPAY_GLO_COMMON_MERCHANT_ID=$ENVPAY_GLO_COMMON_MERCHANT_ID
      ENVPAY_GLO_COMMON_SECRET=$ENVPAY_GLO_COMMON_SECRET
      ENVPAY_PAY_COMMON_SANDBOX_ACCOUNT=$ENVPAY_PAY_COMMON_SANDBOX_ACCOUNT
      PAYU_NGALL2BE_SANDBOX_APP_ID=$PAYU_NGALL2BE_SANDBOX_APP_ID
      PAYU_NGALL2BE_SANDBOX_PRIVATE_KEY=$PAYU_NGALL2BE_SANDBOX_PRIVATE_KEY
      PAYU_KEALL2BE_SANDBOX_APP_ID=$PAYU_KEALL2BE_SANDBOX_APP_ID
      PAYU_KEALL2BE_SANDBOX_PRIVATE_KEY=$PAYU_KEALL2BE_SANDBOX_PRIVATE_KEY
      PAYU_NGALL2BE_APP_ID=$PAYU_NGALL2BE_APP_ID
      PAYU_NGALL2BE_PRIVATE_KEY=$PAYU_NGALL2BE_PRIVATE_KEY
      PAYU_KEALL2BE_APP_ID=$PAYU_KEALL2BE_APP_ID
      PAYU_KEALL2BE_PRIVATE_KEY=$PAYU_KEALL2BE_PRIVATE_KEY
      SANDBOX_PAYFORT_MERCHANT_ID=$SANDBOX_PAYFORT_MERCHANT_ID
      SANDBOX_PAYFORT_ACCESS_CODE=$SANDBOX_PAYFORT_ACCESS_CODE
      SANDBOX_PAYFORT_REQUEST_PHRASE=$SANDBOX_PAYFORT_REQUEST_PHRASE
      SANDBOX_PAYFORT_RESPONSE_PHRASE=$SANDBOX_PAYFORT_RESPONSE_PHRASE
      PAYFORT_MERCHANT_ID=$PAYFORT_MERCHANT_ID
      PAYFORT_ACCESS_CODE=$PAYFORT_ACCESS_CODE
      PAYFORT_REQUEST_PHRASE=$PAYFORT_REQUEST_PHRASE
      PAYFORT_RESPONSE_PHRASE=$PAYFORT_RESPONSE_PHRASE
      BANK_PAYMENT_SECRET=$BANK_PAYMENT_SECRET
      MEMORY_REQUEST=$MEMORY_REQUEST
      MEMORY_LIMIT=$MEMORY_LIMIT
      HOSTNAME_HTTPS=$HOSTNAME_HTTPS | oc apply -f -
    - oc start-build $APPLICATION_NAME  --from-dir=. --follow
  environment:
    name: $ENV

deploy-instance-manual:
  extends: .deploy-instance
  variables:
    INSTANCE: $PROJECT
  when: manual
  only:
    variables:
      - $PROJECT
  except:
    variables:
      - $AUTODEPLOY
  environment:
    name: $ENV

deploy-instance-auto:
  extends: .deploy-instance
  variables:
    INSTANCE: $PROJECT
  only:
    variables:
      - $AUTODEPLOY
  environment:
    name: $ENV

deploy-instance-master:
  extends: .deploy-instance
  variables:
    PROJECT: $PROJECT
    INSTANCE: $PROJECT
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'master'
  except:
    variables:
      - $AUTODEPLOY

deploy-instance-staging:
  extends: .deploy-instance
  variables:
    PROJECT: $PROJECT
    INSTANCE: $PROJECT
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'staging'
  except:
    variables:
      - $AUTODEPLOY

rollback:
  extends: .rollback
  script:
    - echo "oc rollout undo dc/$APPLICATION_NAME" # ONLY FOR TESTS, REMOVE BEFORE MERGE
  rules:
    - if: '$ROLLBACK == "true"'
      when: on_success
