include:
  - project: 'dev_tls/giza/templates'
    ref: production
    file: 'rollback.gitlab-ci.yml'

image: ${DOCKER_REGISTRY_ADDRESS}/openshift3/ose-cli:${DOCKER_TAG_OSE_CLI}

default:
  tags:
    - tlsdev-aws

variables:
  APPLICATION_NAME: payment-api
  ENV: "IET2"
  APP_ENV: "test"
  PROJECT: "visa-be-dev"
  CLIENT: "schengen-be"
  DATABASE: $DATABASE
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  DIRECTUS_ROUTE: "directus"

stages:
  - build
  - test
  - analyze
  - deploy
  - expose
  - rollback

prepare-instance:
  stage: build
  image: ${DOCKER_REGISTRY_ADDRESS}/tlscontact/composer:${DOCKER_TAG_COMPOSER}
  script:
    - composer install -o
  after_script:
    - rm -rf composer.*
  artifacts:
    paths:
      - ./
    expire_in: 1 hour
  environment:
    name: $ENV
  rules:
    - if: '$ROLLBACK == "true"'
      when: never
    - when: on_success

test-unit:
  stage: test
  image: "${DOCKER_REGISTRY_ADDRESS}/tlscontact/composer:${DOCKER_TAG_COMPOSER}"
  before_script:
    - apk add g++ make zlib-dev autoconf file gcc libc-dev make g++ pkgconf re2c;
    - pecl install xdebug && docker-php-ext-enable xdebug;
    - docker-php-ext-install bcmath;
    - apk add postgresql postgresql-dev;
    - docker-php-ext-install pdo pgsql pdo_pgsql;
    - addgroup -S postgres && adduser -S postgres -G postgres;
    - mkdir -p /var/lib/postgresql/data;
    - mkdir -p /run/postgresql/;
    - chown -R postgres:postgres /run/postgresql/;
    - chmod -R 777 /var/lib/postgresql/data;
    - chown -R postgres:postgres /var/lib/postgresql/data;
    - su postgres -c "initdb /var/lib/postgresql/data; echo 'host all  all    0.0.0.0/0  md5' >> /var/lib/postgresql/data/pg_hba.conf; pg_ctl start -D /var/lib/postgresql/data -l /var/lib/postgresql/log.log;";
    - psql -U postgres -c "CREATE ROLE root WITH SUPERUSER; CREATE ROLE common WITH SUPERUSER; ALTER ROLE root WITH LOGIN; ALTER ROLE root WITH CREATEDB;"
  script: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit unittest-report.xml
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit:
        - unittest-report.xml
    paths:
      - "./"
    expire_in: 3 days

sonarcloud-check:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sed -i -e 's/".*payment-api/"\/builds\/dev_tls\/tlspay\/payment-api/g' coverage-report.clover
    - sed -i -e 's/".*payment-api/"\/builds\/dev_tls\/tlspay\/payment-api/g' unittest-report.xml
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - master
    - develop
  except:
    variables:
      - $ROLLBACK


.deploy-instance:
  variables:
    MEMORY_REQUEST: 100Mi
    MEMORY_LIMIT: 256Mi
  stage: deploy
  only:
    variables:
      - $PROJECT
  before_script:
    - echo $MASTER_PUBLIC_URL
    - oc login --token=$GITLAB_SA_TOKEN --insecure-skip-tls-verify=true $MASTER_PUBLIC_URL
  script:
    - oc project "$PROJECT" 2> /dev/null || oc new-project "$PROJECT"
    - export PAYMENT_SERVICE_URL=`oc get route payment -o jsonpath='{.spec.host}'`
    - export DIRECTUS_HOST=`oc get route ${DIRECTUS_ROUTE} -o jsonpath='{.spec.host}'`
    - export REDIS_HOST=$(oc get svc $PROJECT-redis-cluster-aws -o json | jq -r .spec.externalName)
    - oc process -f ./openshift/payment-api-template.yaml APPLICATION_NAME=$APPLICATION_NAME PROJECT=$INSTANCE
      NAMESPACE=$PROJECT
      APP_ENV=$APP_ENV
      OPENSHIFT_ENV=$ENV
      ROUTE_IP_WHITE_LIST="$ROUTE_IP_WHITE_LIST"
      POSTGRES_DB_HOST="pgbouncer"
      POSTGRES_SECRET_NAME="${PROJECT}-pgcluster-common-secret"
      POSTGRES_ADMIN_SECRET_NAME="${PROJECT}-pgsql-master"
      POSTGRES_PAYMENT_DB_DATABASE="payment-$DATABASE"
      AWS_ACCOUNT_S3="tlspay-s3-account"
      PAYMENT_SERVICE_DOMAIN="https://$PAYMENT_SERVICE_URL"
      DIRECTUS_DOMAIN="https://${DIRECTUS_HOST}"
      TLSCONTACT_API="$TLSCONTACT_API"
      REDIS_HOST="tls://${REDIS_HOST}"
      CLIENT="$CLIENT"
      KBANK_THBKK2BE_SANDBOX_API_KEY=$KBANK_THBKK2BE_SANDBOX_API_KEY
      KBANK_THBKK2BE_SANDBOX_SECRET=$KBANK_THBKK2BE_SANDBOX_SECRET
      KBANK_THBKK2BE_SANDBOX_MID=$KBANK_THBKK2BE_SANDBOX_MID
      KBANK_THBKK2BE_API_KEY=$KBANK_THBKK2BE_API_KEY
      KBANK_THBKK2BE_SECRET=$KBANK_THBKK2BE_SECRET
      KBANK_THBKK2BE_MID=$KBANK_THBKK2BE_MID
      ENVPAY_CMI_BEmaAll2be_SANDBOX_MERCHANT_ID=$ENVPAY_CMI_BEmaAll2be_SANDBOX_MERCHANT_ID
      ENVPAY_CMI_BEmaAll2be_SANDBOX_STOREKEY=$ENVPAY_CMI_BEmaAll2be_SANDBOX_STOREKEY
      ENVPAY_CMI_BEmaAll2be_MERCHANT_ID=$ENVPAY_CMI_BEmaAll2be_MERCHANT_ID
      ENVPAY_CMI_BEmaAll2be_STOREKEY=$ENVPAY_CMI_BEmaAll2be_STOREKEY
      ENVPAY_TINGG_COMMON_SANDBOX_ACCOUNT_NUMBER=$ENVPAY_TINGG_COMMON_SANDBOX_ACCOUNT_NUMBER
      ENVPAY_TINGG_COMMON_SANDBOX_SERVICE_CODE=$ENVPAY_TINGG_COMMON_SANDBOX_SERVICE_CODE
      ENVPAY_TINGG_COMMON_SANDBOX_IVKEY=$ENVPAY_TINGG_COMMON_SANDBOX_IVKEY
      ENVPAY_TINGG_COMMON_SANDBOX_SECRET_KEY=$ENVPAY_TINGG_COMMON_SANDBOX_SECRET_KEY
      ENVPAY_TINGG_COMMON_SANDBOX_ACCESS_KEY=$ENVPAY_TINGG_COMMON_SANDBOX_ACCESS_KEY
      ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_ID=$ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_ID
      ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_SECRET=$ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_SECRET
      ENVPAY_TINGG_COMMON_SANDBOX_OAUTH_HOST=$ENVPAY_TINGG_COMMON_SANDBOX_OAUTH_HOST
      ENVPAY_TINGG_COMMON_SANDBOX_QUERY_STATUS_HOST=$ENVPAY_TINGG_COMMON_SANDBOX_QUERY_STATUS_HOST
      ENVPAY_TINGG_COMMON_ACCOUNT_NUMBER=$ENVPAY_TINGG_COMMON_ACCOUNT_NUMBER
      ENVPAY_TINGG_COMMON_SERVICE_CODE=$ENVPAY_TINGG_COMMON_SERVICE_CODE
      ENVPAY_TINGG_COMMON_IVKEY=$ENVPAY_TINGG_COMMON_IVKEY
      ENVPAY_TINGG_COMMON_SECRET_KEY=$ENVPAY_TINGG_COMMON_SECRET_KEY
      ENVPAY_TINGG_COMMON_ACCESS_KEY=$ENVPAY_TINGG_COMMON_ACCESS_KEY
      ENVPAY_TINGG_COMMON_CLIENT_ID=$ENVPAY_TINGG_COMMON_CLIENT_ID
      ENVPAY_TINGG_COMMON_CLIENT_SECRET=$ENVPAY_TINGG_COMMON_CLIENT_SECRET
      ENVPAY_TINGG_COMMON_OAUTH_HOST=$ENVPAY_TINGG_COMMON_OAUTH_HOST
      ENVPAY_TINGG_COMMON_QUERY_STATUS_HOST=$ENVPAY_TINGG_COMMON_QUERY_STATUS_HOST
      PAYGATE_ZAALL2BE_ENCRYPTION_SANDBOX_KEY=$PAYGATE_ZAALL2BE_ENCRYPTION_SANDBOX_KEY
      PAYGATE_ZAALL2BE_SANDBOX_ID=$PAYGATE_ZAALL2BE_SANDBOX_ID
      PAYGATE_ZAALL2BE_ENCRYPTION_KEY=$PAYGATE_ZAALL2BE_ENCRYPTION_KEY
      PAYGATE_ZAALL2BE_ID=$PAYGATE_ZAALL2BE_ID
      PAYGATE_ZAALL2BE_SELLER_EMAIL=$PAYGATE_ZAALL2BE_SELLER_EMAIL
      FAW_COMMON_SANDBOX_MERCHANT_ID=$FAW_COMMON_SANDBOX_MERCHANT_ID
      FAW_COMMON_SANDBOX_SECRET_KEY=$FAW_COMMON_SANDBOX_SECRET_KEY
      FAW_egAll2be_MERCHANT_ID=$FAW_egAll2be_MERCHANT_ID
      FAW_egAll2be_SECURITY_KEY=$FAW_egAll2be_SECURITY_KEY
      ENVPAY_GLO_COMMON_SANDBOX_MERCHANT_ID=$ENVPAY_GLO_COMMON_SANDBOX_MERCHANT_ID
      ENVPAY_GLO_COMMON_SANDBOX_SECRET=$ENVPAY_GLO_COMMON_SANDBOX_SECRET
      ENVPAY_GLO_BEgbALL2be_ACCOUNT=$ENVPAY_GLO_BEgbALL2be_ACCOUNT
      ENVPAY_GLO_COMMON_MERCHANT_ID=$ENVPAY_GLO_COMMON_MERCHANT_ID
      ENVPAY_GLO_COMMON_SECRET=$ENVPAY_GLO_COMMON_SECRET
      ENVPAY_PAY_COMMON_SANDBOX_ACCOUNT=$ENVPAY_PAY_COMMON_SANDBOX_ACCOUNT
      PAYU_NGALL2BE_SANDBOX_APP_ID=$PAYU_NGALL2BE_SANDBOX_APP_ID
      PAYU_NGALL2BE_SANDBOX_PRIVATE_KEY=$PAYU_NGALL2BE_SANDBOX_PRIVATE_KEY
      PAYU_KENYA_SANDBOX_APP_ID=$PAYU_KENYA_SANDBOX_APP_ID
      PAYU_KENYA_SANDBOX_PRIVATE_KEY=$PAYU_KENYA_SANDBOX_PRIVATE_KEY
      PAYU_NGALL2BE_APP_ID=$PAYU_NGALL2BE_APP_ID
      PAYU_NGALL2BE_PRIVATE_KEY=$PAYU_NGALL2BE_PRIVATE_KEY
      PAYU_KEALL2BE_APP_ID=$PAYU_KEALL2BE_APP_ID
      PAYU_KEALL2BE_PRIVATE_KEY=$PAYU_KEALL2BE_PRIVATE_KEY
      PAYU_KEALL2DE_APP_ID=$PAYU_KEALL2DE_APP_ID
      PAYU_KEALL2DE_PRIVATE_KEY=$PAYU_KEALL2DE_PRIVATE_KEY
      SANDBOX_PAYFORT_MERCHANT_ID=$SANDBOX_PAYFORT_MERCHANT_ID
      SANDBOX_PAYFORT_ACCESS_CODE=$SANDBOX_PAYFORT_ACCESS_CODE
      SANDBOX_PAYFORT_REQUEST_PHRASE=$SANDBOX_PAYFORT_REQUEST_PHRASE
      SANDBOX_PAYFORT_RESPONSE_PHRASE=$SANDBOX_PAYFORT_RESPONSE_PHRASE
      PAYFORT_MERCHANT_ID=$PAYFORT_MERCHANT_ID
      PAYFORT_ACCESS_CODE=$PAYFORT_ACCESS_CODE
      PAYFORT_REQUEST_PHRASE=$PAYFORT_REQUEST_PHRASE
      PAYFORT_RESPONSE_PHRASE=$PAYFORT_RESPONSE_PHRASE
      CLICTOPAY_SANDBOX_USER_NAME=$CLICTOPAY_SANDBOX_USER_NAME
      CLICTOPAY_SANDBOX_PASSWORD=$CLICTOPAY_SANDBOX_PASSWORD
      CLICTOPAY_USER_NAME=$CLICTOPAY_USER_NAME
      CLICTOPAY_PASSWORD=$CLICTOPAY_PASSWORD
      BANK_PAYMENT_SECRET=$BANK_PAYMENT_SECRET
      ENVPAY_PAYSOFT_COMMON_SANDBOX_HOST=$ENVPAY_PAYSOFT_COMMON_SANDBOX_HOST
      ENVPAY_PAYSOFT_COMMON_SANDBOX_MERCHANT_ID=$ENVPAY_PAYSOFT_COMMON_SANDBOX_MERCHANT_ID
      ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_ALGORITHM=$ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_ALGORITHM
      ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_SECRET_KEY=$ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_SECRET_KEY
      ENVPAY_PAYSOFT_uaKBP2pl_HOST=$ENVPAY_PAYSOFT_uaKBP2pl_HOST
      ENVPAY_PAYSOFT_uaKBP2pl_MERCHANT_ID=$ENVPAY_PAYSOFT_uaKBP2pl_MERCHANT_ID
      ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_ALGORITHM=$ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_ALGORITHM
      ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_SECRET_KEY=$ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_SECRET_KEY
      ENVPAY_PAYGATE_ZAALL2DE_ENCRYPTION_KEY=$ENVPAY_PAYGATE_ZAALL2DE_ENCRYPTION_KEY
      ENVPAY_PAYGATE_ZAALL2DE_ID=$ENVPAY_PAYGATE_ZAALL2DE_ID
      ENVPAY_PAYGATE_ZAALL2DE_SELLER_EMAIL=$ENVPAY_PAYGATE_ZAALL2DE_SELLER_EMAIL
      ENVPAY_GLO_DEgbALL2de_ACCOUNT=$ENVPAY_GLO_DEgbALL2de_ACCOUNT
      MEMORY_REQUEST=$MEMORY_REQUEST
      MEMORY_LIMIT=$MEMORY_LIMIT
      ENVPAY_SWITCH_COMMON_SANDBOX_HOST=$ENVPAY_SWITCH_COMMON_SANDBOX_HOST
      ENVPAY_SWITCH_COMMON_SANDBOX_ENTITY_ID=$ENVPAY_SWITCH_COMMON_SANDBOX_ENTITY_ID
      ENVPAY_SWITCH_COMMON_SANDBOX_ACCESS_TOKEN=$ENVPAY_SWITCH_COMMON_SANDBOX_ACCESS_TOKEN
      ENVPAY_SWITCH_iqAll2be_HOST=$ENVPAY_SWITCH_iqAll2be_HOST
      ENVPAY_SWITCH_iqAll2be_ENTITY_ID=$ENVPAY_SWITCH_iqAll2be_ENTITY_ID
      ENVPAY_SWITCH_iqAll2be_ACCESS_TOKEN=$ENVPAY_SWITCH_iqAll2be_ACCESS_TOKEN
      ALIPAY_PRODUCT_CODE=$ALIPAY_PRODUCT_CODE
      ALIPAY_METHOD=$ALIPAY_METHOD
      ALIPAY_SANDBOX_APP_ID=$ALIPAY_SANDBOX_APP_ID
      ALIPAY_SANDBOX_GATEWAY=$ALIPAY_SANDBOX_GATEWAY
      ALIPAY_SANDBOX_PRIVATE_KEY=$ALIPAY_SANDBOX_PRIVATE_KEY
      ALIPAY_SANDBOX_PUBLIC_KEY=$ALIPAY_SANDBOX_PUBLIC_KEY
      ALI_DEcnBJS2de_APP_ID=$ALI_DEcnBJS2de_APP_ID
      ALIPAY_GATEWAY=$ALIPAY_GATEWAY
      ALI_DEcnBJS2de_PRIVATE_KEY=$ALI_DEcnBJS2de_PRIVATE_KEY
      ALI_DEcnBJS2de_PUBLIC_KEY=$ALI_DEcnBJS2de_PUBLIC_KEY
      HOSTNAME_HTTPS=$HOSTNAME_HTTPS | oc apply -f -
    - oc start-build $APPLICATION_NAME  --from-dir=. -w
    - oc rollout status dc/$APPLICATION_NAME -w
    - oc process -f ./openshift/payment-fawry-queue-template.yaml APPLICATION_NAME=$APPLICATION_NAME PROJECT=$INSTANCE
      NAMESPACE=$PROJECT
      APP_ENV=$APP_ENV
      OPENSHIFT_ENV=$ENV
      ROUTE_IP_WHITE_LIST="$ROUTE_IP_WHITE_LIST"
      POSTGRES_DB_HOST="pgbouncer"
      POSTGRES_SECRET_NAME="${PROJECT}-pgcluster-common-secret"
      POSTGRES_ADMIN_SECRET_NAME="${PROJECT}-pgsql-master"
      POSTGRES_PAYMENT_DB_DATABASE="payment-$DATABASE"
      AWS_ACCOUNT_S3="tlspay-s3-account"
      PAYMENT_SERVICE_DOMAIN="https://$PAYMENT_SERVICE_URL"
      DIRECTUS_DOMAIN="https://${DIRECTUS_HOST}"
      REDIS_HOST="tls://${REDIS_HOST}"
      TLSCONTACT_API="$TLSCONTACT_API"
      CLIENT="$CLIENT"
      KBANK_THBKK2BE_SANDBOX_API_KEY=$KBANK_THBKK2BE_SANDBOX_API_KEY
      KBANK_THBKK2BE_SANDBOX_SECRET=$KBANK_THBKK2BE_SANDBOX_SECRET
      KBANK_THBKK2BE_SANDBOX_MID=$KBANK_THBKK2BE_SANDBOX_MID
      KBANK_THBKK2BE_API_KEY=$KBANK_THBKK2BE_API_KEY
      KBANK_THBKK2BE_SECRET=$KBANK_THBKK2BE_SECRET
      KBANK_THBKK2BE_MID=$KBANK_THBKK2BE_MID
      ENVPAY_CMI_BEmaAll2be_SANDBOX_MERCHANT_ID=$ENVPAY_CMI_BEmaAll2be_SANDBOX_MERCHANT_ID
      ENVPAY_CMI_BEmaAll2be_SANDBOX_STOREKEY=$ENVPAY_CMI_BEmaAll2be_SANDBOX_STOREKEY
      ENVPAY_CMI_BEmaAll2be_MERCHANT_ID=$ENVPAY_CMI_BEmaAll2be_MERCHANT_ID
      ENVPAY_CMI_BEmaAll2be_STOREKEY=$ENVPAY_CMI_BEmaAll2be_STOREKEY
      ENVPAY_TINGG_COMMON_SANDBOX_ACCOUNT_NUMBER=$ENVPAY_TINGG_COMMON_SANDBOX_ACCOUNT_NUMBER
      ENVPAY_TINGG_COMMON_SANDBOX_SERVICE_CODE=$ENVPAY_TINGG_COMMON_SANDBOX_SERVICE_CODE
      ENVPAY_TINGG_COMMON_SANDBOX_IVKEY=$ENVPAY_TINGG_COMMON_SANDBOX_IVKEY
      ENVPAY_TINGG_COMMON_SANDBOX_SECRET_KEY=$ENVPAY_TINGG_COMMON_SANDBOX_SECRET_KEY
      ENVPAY_TINGG_COMMON_SANDBOX_ACCESS_KEY=$ENVPAY_TINGG_COMMON_SANDBOX_ACCESS_KEY
      ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_ID=$ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_ID
      ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_SECRET=$ENVPAY_TINGG_COMMON_SANDBOX_CLIENT_SECRET
      ENVPAY_TINGG_COMMON_SANDBOX_OAUTH_HOST=$ENVPAY_TINGG_COMMON_SANDBOX_OAUTH_HOST
      ENVPAY_TINGG_COMMON_SANDBOX_QUERY_STATUS_HOST=$ENVPAY_TINGG_COMMON_SANDBOX_QUERY_STATUS_HOST
      ENVPAY_TINGG_COMMON_ACCOUNT_NUMBER=$ENVPAY_TINGG_COMMON_ACCOUNT_NUMBER
      ENVPAY_TINGG_COMMON_SERVICE_CODE=$ENVPAY_TINGG_COMMON_SERVICE_CODE
      ENVPAY_TINGG_COMMON_IVKEY=$ENVPAY_TINGG_COMMON_IVKEY
      ENVPAY_TINGG_COMMON_SECRET_KEY=$ENVPAY_TINGG_COMMON_SECRET_KEY
      ENVPAY_TINGG_COMMON_ACCESS_KEY=$ENVPAY_TINGG_COMMON_ACCESS_KEY
      ENVPAY_TINGG_COMMON_CLIENT_ID=$ENVPAY_TINGG_COMMON_CLIENT_ID
      ENVPAY_TINGG_COMMON_CLIENT_SECRET=$ENVPAY_TINGG_COMMON_CLIENT_SECRET
      ENVPAY_TINGG_COMMON_OAUTH_HOST=$ENVPAY_TINGG_COMMON_OAUTH_HOST
      ENVPAY_TINGG_COMMON_QUERY_STATUS_HOST=$ENVPAY_TINGG_COMMON_QUERY_STATUS_HOST
      PAYGATE_ZAALL2BE_ENCRYPTION_SANDBOX_KEY=$PAYGATE_ZAALL2BE_ENCRYPTION_SANDBOX_KEY
      PAYGATE_ZAALL2BE_SANDBOX_ID=$PAYGATE_ZAALL2BE_SANDBOX_ID
      PAYGATE_ZAALL2BE_ENCRYPTION_KEY=$PAYGATE_ZAALL2BE_ENCRYPTION_KEY
      PAYGATE_ZAALL2BE_ID=$PAYGATE_ZAALL2BE_ID
      PAYGATE_ZAALL2BE_SELLER_EMAIL=$PAYGATE_ZAALL2BE_SELLER_EMAIL
      FAW_COMMON_SANDBOX_MERCHANT_ID=$FAW_COMMON_SANDBOX_MERCHANT_ID
      FAW_COMMON_SANDBOX_SECRET_KEY=$FAW_COMMON_SANDBOX_SECRET_KEY
      FAW_egAll2be_MERCHANT_ID=$FAW_egAll2be_MERCHANT_ID
      FAW_egAll2be_SECURITY_KEY=$FAW_egAll2be_SECURITY_KEY
      ENVPAY_GLO_COMMON_SANDBOX_MERCHANT_ID=$ENVPAY_GLO_COMMON_SANDBOX_MERCHANT_ID
      ENVPAY_GLO_COMMON_SANDBOX_SECRET=$ENVPAY_GLO_COMMON_SANDBOX_SECRET
      ENVPAY_GLO_BEgbALL2be_ACCOUNT=$ENVPAY_GLO_BEgbALL2be_ACCOUNT
      ENVPAY_GLO_COMMON_MERCHANT_ID=$ENVPAY_GLO_COMMON_MERCHANT_ID
      ENVPAY_GLO_COMMON_SECRET=$ENVPAY_GLO_COMMON_SECRET
      ENVPAY_PAY_COMMON_SANDBOX_ACCOUNT=$ENVPAY_PAY_COMMON_SANDBOX_ACCOUNT
      PAYU_NGALL2BE_SANDBOX_APP_ID=$PAYU_NGALL2BE_SANDBOX_APP_ID
      PAYU_NGALL2BE_SANDBOX_PRIVATE_KEY=$PAYU_NGALL2BE_SANDBOX_PRIVATE_KEY
      PAYU_KENYA_SANDBOX_APP_ID=$PAYU_KENYA_SANDBOX_APP_ID
      PAYU_KENYA_SANDBOX_PRIVATE_KEY=$PAYU_KENYA_SANDBOX_PRIVATE_KEY
      PAYU_NGALL2BE_APP_ID=$PAYU_NGALL2BE_APP_ID
      PAYU_NGALL2BE_PRIVATE_KEY=$PAYU_NGALL2BE_PRIVATE_KEY
      PAYU_KEALL2BE_APP_ID=$PAYU_KEALL2BE_APP_ID
      PAYU_KEALL2BE_PRIVATE_KEY=$PAYU_KEALL2BE_PRIVATE_KEY
      PAYU_KEALL2DE_APP_ID=$PAYU_KEALL2DE_APP_ID
      PAYU_KEALL2DE_PRIVATE_KEY=$PAYU_KEALL2DE_PRIVATE_KEY
      SANDBOX_PAYFORT_MERCHANT_ID=$SANDBOX_PAYFORT_MERCHANT_ID
      SANDBOX_PAYFORT_ACCESS_CODE=$SANDBOX_PAYFORT_ACCESS_CODE
      SANDBOX_PAYFORT_REQUEST_PHRASE=$SANDBOX_PAYFORT_REQUEST_PHRASE
      SANDBOX_PAYFORT_RESPONSE_PHRASE=$SANDBOX_PAYFORT_RESPONSE_PHRASE
      PAYFORT_MERCHANT_ID=$PAYFORT_MERCHANT_ID
      PAYFORT_ACCESS_CODE=$PAYFORT_ACCESS_CODE
      PAYFORT_REQUEST_PHRASE=$PAYFORT_REQUEST_PHRASE
      PAYFORT_RESPONSE_PHRASE=$PAYFORT_RESPONSE_PHRASE
      CLICTOPAY_SANDBOX_USER_NAME=$CLICTOPAY_SANDBOX_USER_NAME
      CLICTOPAY_SANDBOX_PASSWORD=$CLICTOPAY_SANDBOX_PASSWORD
      CLICTOPAY_USER_NAME=$CLICTOPAY_USER_NAME
      CLICTOPAY_PASSWORD=$CLICTOPAY_PASSWORD
      BANK_PAYMENT_SECRET=$BANK_PAYMENT_SECRET
      ENVPAY_PAYSOFT_COMMON_SANDBOX_HOST=$ENVPAY_PAYSOFT_COMMON_SANDBOX_HOST
      ENVPAY_PAYSOFT_COMMON_SANDBOX_MERCHANT_ID=$ENVPAY_PAYSOFT_COMMON_SANDBOX_MERCHANT_ID
      ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_ALGORITHM=$ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_ALGORITHM
      ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_SECRET_KEY=$ENVPAY_PAYSOFT_COMMON_SANDBOX_SIGNATURE_SECRET_KEY
      ENVPAY_PAYSOFT_uaKBP2pl_HOST=$ENVPAY_PAYSOFT_uaKBP2pl_HOST
      ENVPAY_PAYSOFT_uaKBP2pl_MERCHANT_ID=$ENVPAY_PAYSOFT_uaKBP2pl_MERCHANT_ID
      ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_ALGORITHM=$ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_ALGORITHM
      ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_SECRET_KEY=$ENVPAY_PAYSOFT_uaKBP2pl_SIGNATURE_SECRET_KEY
      ENVPAY_PAYGATE_ZAALL2DE_ENCRYPTION_KEY=$ENVPAY_PAYGATE_ZAALL2DE_ENCRYPTION_KEY
      ENVPAY_PAYGATE_ZAALL2DE_ID=$ENVPAY_PAYGATE_ZAALL2DE_ID
      ENVPAY_PAYGATE_ZAALL2DE_SELLER_EMAIL=$ENVPAY_PAYGATE_ZAALL2DE_SELLER_EMAIL
      ENVPAY_GLO_DEgbALL2de_ACCOUNT=$ENVPAY_GLO_DEgbALL2de_ACCOUNT
      MEMORY_REQUEST=$MEMORY_REQUEST
      MEMORY_LIMIT=$MEMORY_LIMIT
      ENVPAY_SWITCH_COMMON_SANDBOX_HOST=$ENVPAY_SWITCH_COMMON_SANDBOX_HOST
      ENVPAY_SWITCH_COMMON_SANDBOX_ENTITY_ID=$ENVPAY_SWITCH_COMMON_SANDBOX_ENTITY_ID
      ENVPAY_SWITCH_COMMON_SANDBOX_ACCESS_TOKEN=$ENVPAY_SWITCH_COMMON_SANDBOX_ACCESS_TOKEN
      ENVPAY_SWITCH_iqAll2be_HOST=$ENVPAY_SWITCH_iqAll2be_HOST
      ENVPAY_SWITCH_iqAll2be_ENTITY_ID=$ENVPAY_SWITCH_iqAll2be_ENTITY_ID
      ENVPAY_SWITCH_iqAll2be_ACCESS_TOKEN=$ENVPAY_SWITCH_iqAll2be_ACCESS_TOKEN
      ALIPAY_PRODUCT_CODE=$ALIPAY_PRODUCT_CODE
      ALIPAY_METHOD=$ALIPAY_METHOD
      ALIPAY_SANDBOX_APP_ID=$ALIPAY_SANDBOX_APP_ID
      ALIPAY_SANDBOX_GATEWAY=$ALIPAY_SANDBOX_GATEWAY
      ALIPAY_SANDBOX_PRIVATE_KEY=$ALIPAY_SANDBOX_PRIVATE_KEY
      ALIPAY_SANDBOX_PUBLIC_KEY=$ALIPAY_SANDBOX_PUBLIC_KEY
      ALI_DEcnBJS2de_APP_ID=$ALI_DEcnBJS2de_APP_ID
      ALIPAY_GATEWAY=$ALIPAY_GATEWAY
      ALI_DEcnBJS2de_PRIVATE_KEY=$ALI_DEcnBJS2de_PRIVATE_KEY
      ALI_DEcnBJS2de_PUBLIC_KEY=$ALI_DEcnBJS2de_PUBLIC_KEY
      HOSTNAME_HTTPS=$HOSTNAME_HTTPS | oc apply -f -

  environment:
    name: $ENV

deploy-instance-manual:
  extends: .deploy-instance
  variables:
    INSTANCE: $PROJECT
  when: manual
  only:
    variables:
      - $PROJECT
  except:
    variables:
      - $AUTODEPLOY
      - $ROLLBACK
  environment:
    name: $ENV

deploy-instance-auto:
  extends: .deploy-instance
  variables:
    INSTANCE: $PROJECT
  only:
    variables:
      - $AUTODEPLOY
  except:
    variables:
      - $ROLLBACK
  environment:
    name: $ENV

deploy-instance-master:
  extends: .deploy-instance
  variables:
    INSTANCE: $PROJECT
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'master'
  except:
    variables:
      - $AUTODEPLOY
      - $ROLLBACK

deploy-instance-staging:
  extends: .deploy-instance
  variables:
    INSTANCE: $PROJECT
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'staging'
  except:
    variables:
      - $AUTODEPLOY
      - $ROLLBACK

rollback:
  extends: .rollback
  script:
    - oc rollout undo dc/$APPLICATION_NAME
  rules:
    - if: '$ROLLBACK == "true"'
      when: on_success
