<?php

return [
    'ci' => [
        'gc_id' => 'ci',
        'gc_phone_prefix' => '@225',
        'gc_name' => "Cote d'Ivoire",
        'gc_long_name' => "Republic of Cote d'Ivoire",
        'gc_continent' => 'AF',
        'gc_iso_3' => 'civ',
    ],
    'st' => [
        'gc_id' => 'st',
        'gc_phone_prefix' => '@239',
        'gc_name' => 'Sao Tome and Principe',
        'gc_long_name' => 'Democratic Republic of Sao Tome and Principe',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'stp',
    ],
    'bl' => [
        'gc_id' => 'bl',
        'gc_phone_prefix' => '@590',
        'gc_name' => 'Saint Barthelemy',
        'gc_long_name' => 'Collectivity of Saint Barthélemy',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'blm',
    ],
    '??' => [
        'gc_id' => '??',
        'gc_phone_prefix' => '@',
        'gc_name' => 'N/A',
        'gc_long_name' => 'N/A',
        'gc_continent' => '??',
        'gc_iso_3' => '???',
    ],
    'af' => [
        'gc_id' => 'af',
        'gc_phone_prefix' => '@093',
        'gc_name' => 'Afghanistan',
        'gc_long_name' => 'The Islamic Republic of Afghanistan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'afg',
    ],
    'za' => [
        'gc_id' => 'za',
        'gc_phone_prefix' => '@027',
        'gc_name' => 'South Africa',
        'gc_long_name' => 'Republic of South Africa',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'zaf',
    ],
    'al' => [
        'gc_id' => 'al',
        'gc_phone_prefix' => '@355',
        'gc_name' => 'Albania',
        'gc_long_name' => 'Republic of Albania',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'alb',
    ],
    'de' => [
        'gc_id' => 'de',
        'gc_phone_prefix' => '@049',
        'gc_name' => 'Germany',
        'gc_long_name' => 'Federal Republic of Germany',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'deu',
    ],
    'dz' => [
        'gc_id' => 'dz',
        'gc_phone_prefix' => '@213',
        'gc_name' => 'Algeria',
        'gc_long_name' => "People's Democratic Republic of Algeria",
        'gc_continent' => 'AF',
        'gc_iso_3' => 'dza',
    ],
    'ad' => [
        'gc_id' => 'ad',
        'gc_phone_prefix' => '@376',
        'gc_name' => 'Andorra',
        'gc_long_name' => 'Principality of Andorra',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'and',
    ],
    'ao' => [
        'gc_id' => 'ao',
        'gc_phone_prefix' => '@244',
        'gc_name' => 'Angola',
        'gc_long_name' => 'Republic of Angola',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'ago',
    ],
    'ag' => [
        'gc_id' => 'ag',
        'gc_phone_prefix' => '@811',
        'gc_name' => 'Antigua and Barbuda',
        'gc_long_name' => 'Antigua and Barbuda',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'atg',
    ],
    'sa' => [
        'gc_id' => 'sa',
        'gc_phone_prefix' => '@966',
        'gc_name' => 'Saudi Arabia',
        'gc_long_name' => 'Kingdom of Saudi Arabia',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'sau',
    ],
    'ar' => [
        'gc_id' => 'ar',
        'gc_phone_prefix' => '@054',
        'gc_name' => 'Argentina',
        'gc_long_name' => 'Argentine Republic',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'arg',
    ],
    'am' => [
        'gc_id' => 'am',
        'gc_phone_prefix' => '@374',
        'gc_name' => 'Armenia',
        'gc_long_name' => 'Republic of Armenia',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'arm',
    ],
    'au' => [
        'gc_id' => 'au',
        'gc_phone_prefix' => '@061',
        'gc_name' => 'Australia',
        'gc_long_name' => 'Commonwealth of Australia',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'aus',
    ],
    'at' => [
        'gc_id' => 'at',
        'gc_phone_prefix' => '@043',
        'gc_name' => 'Austria',
        'gc_long_name' => 'Republic of Austria',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'aut',
    ],
    'az' => [
        'gc_id' => 'az',
        'gc_phone_prefix' => '@994',
        'gc_name' => 'Azerbaijan',
        'gc_long_name' => 'Republic of Azerbaijan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'aze',
    ],
    'bs' => [
        'gc_id' => 'bs',
        'gc_phone_prefix' => '@812',
        'gc_name' => 'Bahamas',
        'gc_long_name' => 'Commonwealth of the Bahamas',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'bhs',
    ],
    'bh' => [
        'gc_id' => 'bh',
        'gc_phone_prefix' => '@973',
        'gc_name' => 'Bahrain',
        'gc_long_name' => 'Kingdom of Bahrain',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'bhr',
    ],
    'bd' => [
        'gc_id' => 'bd',
        'gc_phone_prefix' => '@880',
        'gc_name' => 'Bangladesh',
        'gc_long_name' => "People's Republic of Bangladesh",
        'gc_continent' => 'AS',
        'gc_iso_3' => 'bgd',
    ],
    'bb' => [
        'gc_id' => 'bb',
        'gc_phone_prefix' => '@246',
        'gc_name' => 'Barbados',
        'gc_long_name' => 'Barbados',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'brb',
    ],
    'be' => [
        'gc_id' => 'be',
        'gc_phone_prefix' => '@032',
        'gc_name' => 'Belgium',
        'gc_long_name' => 'Kingdom of Belgium',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'bel',
    ],
    'bz' => [
        'gc_id' => 'bz',
        'gc_phone_prefix' => '@501',
        'gc_name' => 'Belize',
        'gc_long_name' => 'Belize',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'blz',
    ],
    'bj' => [
        'gc_id' => 'bj',
        'gc_phone_prefix' => '@229',
        'gc_name' => 'Benin',
        'gc_long_name' => 'Republic of Benin',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'ben',
    ],
    'rs' => [
        'gc_id' => 'rs',
        'gc_phone_prefix' => '@381',
        'gc_name' => 'Serbia',
        'gc_long_name' => 'Republic of Serbia',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'srb',
    ],
    'bt' => [
        'gc_id' => 'bt',
        'gc_phone_prefix' => '@975',
        'gc_name' => 'Bhutan',
        'gc_long_name' => 'Kingdom of Bhutan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'btn',
    ],
    'by' => [
        'gc_id' => 'by',
        'gc_phone_prefix' => '@375',
        'gc_name' => 'Belarus',
        'gc_long_name' => 'Belarus',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'blr',
    ],
    'bo' => [
        'gc_id' => 'bo',
        'gc_phone_prefix' => '@591',
        'gc_name' => 'Bolivia',
        'gc_long_name' => 'Plurinational State of Bolivia',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'bol',
    ],
    'ba' => [
        'gc_id' => 'ba',
        'gc_phone_prefix' => '@387',
        'gc_name' => 'Bosnia and Herzegovina',
        'gc_long_name' => 'Bosnia and Herzegovina',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'bih',
    ],
    'bw' => [
        'gc_id' => 'bw',
        'gc_phone_prefix' => '@267',
        'gc_name' => 'Botswana',
        'gc_long_name' => 'Republic of Botswana',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'bwa',
    ],
    'br' => [
        'gc_id' => 'br',
        'gc_phone_prefix' => '@055',
        'gc_name' => 'Brazil',
        'gc_long_name' => 'Federative Republic of Brazil',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'bra',
    ],
    'bn' => [
        'gc_id' => 'bn',
        'gc_phone_prefix' => '@673',
        'gc_name' => 'Brunei',
        'gc_long_name' => 'Brunei Darussalam',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'brn',
    ],
    'bg' => [
        'gc_id' => 'bg',
        'gc_phone_prefix' => '@359',
        'gc_name' => 'Bulgaria',
        'gc_long_name' => 'Republic of Bulgaria',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'bgr',
    ],
    'bf' => [
        'gc_id' => 'bf',
        'gc_phone_prefix' => '@226',
        'gc_name' => 'Burkina Faso',
        'gc_long_name' => 'Burkina Faso',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'bfa',
    ],
    'bi' => [
        'gc_id' => 'bi',
        'gc_phone_prefix' => '@257',
        'gc_name' => 'Burundi',
        'gc_long_name' => 'Republic of Burundi',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'bdi',
    ],
    'kh' => [
        'gc_id' => 'kh',
        'gc_phone_prefix' => '@855',
        'gc_name' => 'Cambodia',
        'gc_long_name' => 'Kingdom of Cambodia',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'khm',
    ],
    'cm' => [
        'gc_id' => 'cm',
        'gc_phone_prefix' => '@237',
        'gc_name' => 'Cameroon',
        'gc_long_name' => 'Republic of Cameroon',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'cmr',
    ],
    'ca' => [
        'gc_id' => 'ca',
        'gc_phone_prefix' => '@010',
        'gc_name' => 'Canada',
        'gc_long_name' => 'Canada',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'can',
    ],
    'cv' => [
        'gc_id' => 'cv',
        'gc_phone_prefix' => '@238',
        'gc_name' => 'Cape Verde',
        'gc_long_name' => 'Republic of Cape Verde',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'cpv',
    ],
    'cf' => [
        'gc_id' => 'cf',
        'gc_phone_prefix' => '@236',
        'gc_name' => 'Central African Republic',
        'gc_long_name' => 'Central African Republic',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'caf',
    ],
    'cl' => [
        'gc_id' => 'cl',
        'gc_phone_prefix' => '@056',
        'gc_name' => 'Chile',
        'gc_long_name' => 'Republic of Chile',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'chl',
    ],
    'lk' => [
        'gc_id' => 'lk',
        'gc_phone_prefix' => '@094',
        'gc_name' => 'Sri Lanka',
        'gc_long_name' => 'Democratic Socialist Republic of Sri Lanka',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'lka',
    ],
    'cy' => [
        'gc_id' => 'cy',
        'gc_phone_prefix' => '@357',
        'gc_name' => 'Cyprus',
        'gc_long_name' => 'Republic of Cyprus',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'cyp',
    ],
    'co' => [
        'gc_id' => 'co',
        'gc_phone_prefix' => '@057',
        'gc_name' => 'Colombia',
        'gc_long_name' => 'Republic of Colombia',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'col',
    ],
    'km' => [
        'gc_id' => 'km',
        'gc_phone_prefix' => '@269',
        'gc_name' => 'Comoros',
        'gc_long_name' => 'Union of the Comoros',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'com',
    ],
    'cg' => [
        'gc_id' => 'cg',
        'gc_phone_prefix' => '@242',
        'gc_name' => 'Congo',
        'gc_long_name' => 'Congo, Republic of',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'cog',
    ],
    'cd' => [
        'gc_id' => 'cd',
        'gc_phone_prefix' => '@243',
        'gc_name' => 'DR Congo',
        'gc_long_name' => 'Congo, The Democratic Republic of the',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'cod',
    ],
    'kp' => [
        'gc_id' => 'kp',
        'gc_phone_prefix' => '@850',
        'gc_name' => 'North Korea',
        'gc_long_name' => "Democratic People's Republic of Korea",
        'gc_continent' => 'AS',
        'gc_iso_3' => 'prk',
    ],
    'kr' => [
        'gc_id' => 'kr',
        'gc_phone_prefix' => '@082',
        'gc_name' => 'South Korea',
        'gc_long_name' => 'Republic of Korea',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'kor',
    ],
    'cr' => [
        'gc_id' => 'cr',
        'gc_phone_prefix' => '@506',
        'gc_name' => 'Costa Rica',
        'gc_long_name' => 'Republic of Costa Rica',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'cri',
    ],
    'hr' => [
        'gc_id' => 'hr',
        'gc_phone_prefix' => '@385',
        'gc_name' => 'Croatia',
        'gc_long_name' => 'Republic of Croatia',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'hrv',
    ],
    'cu' => [
        'gc_id' => 'cu',
        'gc_phone_prefix' => '@053',
        'gc_name' => 'Cuba',
        'gc_long_name' => 'Republic of Cuba',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'cub',
    ],
    'dk' => [
        'gc_id' => 'dk',
        'gc_phone_prefix' => '@045',
        'gc_name' => 'Denmark',
        'gc_long_name' => 'Kingdom of Denmark',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'dnk',
    ],
    'dj' => [
        'gc_id' => 'dj',
        'gc_phone_prefix' => '@253',
        'gc_name' => 'Djibouti',
        'gc_long_name' => 'Republic of Djibouti',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'dji',
    ],
    'do' => [
        'gc_id' => 'do',
        'gc_phone_prefix' => '@809',
        'gc_name' => 'Dominican Republic',
        'gc_long_name' => 'Dominican Republic',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'dom',
    ],
    'dm' => [
        'gc_id' => 'dm',
        'gc_phone_prefix' => '@813',
        'gc_name' => 'Dominica',
        'gc_long_name' => 'Commonwealth of Dominica',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'dma',
    ],
    'eg' => [
        'gc_id' => 'eg',
        'gc_phone_prefix' => '@020',
        'gc_name' => 'Egypt',
        'gc_long_name' => 'Arab Republic of Egypt',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'egy',
    ],
    'ae' => [
        'gc_id' => 'ae',
        'gc_phone_prefix' => '@971',
        'gc_name' => 'United Arab Emirates',
        'gc_long_name' => 'United Arab Emirates',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'are',
    ],
    'ec' => [
        'gc_id' => 'ec',
        'gc_phone_prefix' => '@593',
        'gc_name' => 'Ecuador',
        'gc_long_name' => 'Republic of Ecuador',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'ecu',
    ],
    'er' => [
        'gc_id' => 'er',
        'gc_phone_prefix' => '@291',
        'gc_name' => 'Eritrea',
        'gc_long_name' => 'State of Eritrea',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'eri',
    ],
    'es' => [
        'gc_id' => 'es',
        'gc_phone_prefix' => '@034',
        'gc_name' => 'Spain',
        'gc_long_name' => 'Kingdom of Spain',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'esp',
    ],
    'ee' => [
        'gc_id' => 'ee',
        'gc_phone_prefix' => '@372',
        'gc_name' => 'Estonia',
        'gc_long_name' => 'Republic of Estonia',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'est',
    ],
    'us' => [
        'gc_id' => 'us',
        'gc_phone_prefix' => '@001',
        'gc_name' => 'United States',
        'gc_long_name' => 'United States of America',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'usa',
    ],
    'et' => [
        'gc_id' => 'et',
        'gc_phone_prefix' => '@251',
        'gc_name' => 'Ethiopia',
        'gc_long_name' => 'Federal Democratic Republic of Ethiopia',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'eth',
    ],
    'fj' => [
        'gc_id' => 'fj',
        'gc_phone_prefix' => '@679',
        'gc_name' => 'Fiji',
        'gc_long_name' => 'Republic of the Fiji Islands',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'fji',
    ],
    'fi' => [
        'gc_id' => 'fi',
        'gc_phone_prefix' => '@358',
        'gc_name' => 'Finland',
        'gc_long_name' => 'Republic of Finland',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'fin',
    ],
    'fr' => [
        'gc_id' => 'fr',
        'gc_phone_prefix' => '@033',
        'gc_name' => 'France',
        'gc_long_name' => 'French Republic',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'fra',
    ],
    'ga' => [
        'gc_id' => 'ga',
        'gc_phone_prefix' => '@241',
        'gc_name' => 'Gabon',
        'gc_long_name' => 'Gabonese Republic',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'gab',
    ],
    'gm' => [
        'gc_id' => 'gm',
        'gc_phone_prefix' => '@220',
        'gc_name' => 'Gambia',
        'gc_long_name' => 'Republic of the Gambia',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'gmb',
    ],
    'ge' => [
        'gc_id' => 'ge',
        'gc_phone_prefix' => '@995',
        'gc_name' => 'Georgia',
        'gc_long_name' => 'Georgia',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'geo',
    ],
    'gh' => [
        'gc_id' => 'gh',
        'gc_phone_prefix' => '@233',
        'gc_name' => 'Ghana',
        'gc_long_name' => 'Republic of Ghana',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'gha',
    ],
    'me' => [
        'gc_id' => 'me',
        'gc_phone_prefix' => '@382',
        'gc_name' => 'Montenegro',
        'gc_long_name' => 'Montenegro',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'mne',
    ],
    'gr' => [
        'gc_id' => 'gr',
        'gc_phone_prefix' => '@030',
        'gc_name' => 'Greece',
        'gc_long_name' => 'Hellenic Republic',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'grc',
    ],
    'gd' => [
        'gc_id' => 'gd',
        'gc_phone_prefix' => '@814',
        'gc_name' => 'Grenada',
        'gc_long_name' => 'Grenada',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'grd',
    ],
    'gt' => [
        'gc_id' => 'gt',
        'gc_phone_prefix' => '@502',
        'gc_name' => 'Guatemala',
        'gc_long_name' => 'Republic of Guatemala',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'gtm',
    ],
    'gn' => [
        'gc_id' => 'gn',
        'gc_phone_prefix' => '@224',
        'gc_name' => 'Guinea',
        'gc_long_name' => 'Republic of Guinea',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'gin',
    ],
    'gw' => [
        'gc_id' => 'gw',
        'gc_phone_prefix' => '@245',
        'gc_name' => 'Guinea-Bissau',
        'gc_long_name' => 'Republic of Guinea-Bissau',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'gnb',
    ],
    'gq' => [
        'gc_id' => 'gq',
        'gc_phone_prefix' => '@240',
        'gc_name' => 'Equatorial Guinea',
        'gc_long_name' => 'Republic of  Equatorial Guinea',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'gnq',
    ],
    'gy' => [
        'gc_id' => 'gy',
        'gc_phone_prefix' => '@592',
        'gc_name' => 'Guyana',
        'gc_long_name' => 'Co-operative Republic of Guyana',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'guy',
    ],
    'ht' => [
        'gc_id' => 'ht',
        'gc_phone_prefix' => '@509',
        'gc_name' => 'Haiti',
        'gc_long_name' => 'Republic of Haiti',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'hti',
    ],
    'hn' => [
        'gc_id' => 'hn',
        'gc_phone_prefix' => '@504',
        'gc_name' => 'Honduras',
        'gc_long_name' => 'Republic of Honduras',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'hnd',
    ],
    'se' => [
        'gc_id' => 'se',
        'gc_phone_prefix' => '@046',
        'gc_name' => 'Sweden',
        'gc_long_name' => 'Kingdom of Sweden',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'swe',
    ],
    'hu' => [
        'gc_id' => 'hu',
        'gc_phone_prefix' => '@036',
        'gc_name' => 'Hungary',
        'gc_long_name' => 'Republic of Hungary',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'hun',
    ],
    'in' => [
        'gc_id' => 'in',
        'gc_phone_prefix' => '@091',
        'gc_name' => 'India',
        'gc_long_name' => 'Republic of India',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'ind',
    ],
    'id' => [
        'gc_id' => 'id',
        'gc_phone_prefix' => '@062',
        'gc_name' => 'Indonesia',
        'gc_long_name' => 'Republic of Indonesia',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'idn',
    ],
    'iq' => [
        'gc_id' => 'iq',
        'gc_phone_prefix' => '@964',
        'gc_name' => 'Iraq',
        'gc_long_name' => 'Republic of Iraq',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'irq',
    ],
    'ir' => [
        'gc_id' => 'ir',
        'gc_phone_prefix' => '@098',
        'gc_name' => 'Iran',
        'gc_long_name' => 'Islamic Republic of Iran',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'irn',
    ],
    'ie' => [
        'gc_id' => 'ie',
        'gc_phone_prefix' => '@353',
        'gc_name' => 'Ireland',
        'gc_long_name' => 'Ireland',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'irl',
    ],
    'is' => [
        'gc_id' => 'is',
        'gc_phone_prefix' => '@354',
        'gc_name' => 'Iceland',
        'gc_long_name' => 'Republic of Iceland',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'isl',
    ],
    'il' => [
        'gc_id' => 'il',
        'gc_phone_prefix' => '@097',
        'gc_name' => 'Israel',
        'gc_long_name' => 'State of Israel',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'isr',
    ],
    'it' => [
        'gc_id' => 'it',
        'gc_phone_prefix' => '@039',
        'gc_name' => 'Italy',
        'gc_long_name' => 'Italian Republic',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'ita',
    ],
    'jm' => [
        'gc_id' => 'jm',
        'gc_phone_prefix' => '@817',
        'gc_name' => 'Jamaica',
        'gc_long_name' => 'Jamaica',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'jam',
    ],
    'jp' => [
        'gc_id' => 'jp',
        'gc_phone_prefix' => '@081',
        'gc_name' => 'Japan',
        'gc_long_name' => 'Japan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'jpn',
    ],
    'jo' => [
        'gc_id' => 'jo',
        'gc_phone_prefix' => '@962',
        'gc_name' => 'Jordan',
        'gc_long_name' => 'Hashemite Kingdom of Jordan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'jor',
    ],
    'kz' => [
        'gc_id' => 'kz',
        'gc_phone_prefix' => '@073',
        'gc_name' => 'Kazakhstan',
        'gc_long_name' => 'Republic of Kazakhstan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'kaz',
    ],
    'ke' => [
        'gc_id' => 'ke',
        'gc_phone_prefix' => '@254',
        'gc_name' => 'Kenya',
        'gc_long_name' => 'Republic of Kenya',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'ken',
    ],
    'kg' => [
        'gc_id' => 'kg',
        'gc_phone_prefix' => '@996',
        'gc_name' => 'Kyrgyzstan',
        'gc_long_name' => 'Kyrgyz Republic',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'kgz',
    ],
    'ki' => [
        'gc_id' => 'ki',
        'gc_phone_prefix' => '@686',
        'gc_name' => 'Kiribati',
        'gc_long_name' => 'Republic of Kiribati',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'kir',
    ],
    'kw' => [
        'gc_id' => 'kw',
        'gc_phone_prefix' => '@965',
        'gc_name' => 'Kuwait',
        'gc_long_name' => 'State of Kuwait',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'kwt',
    ],
    'la' => [
        'gc_id' => 'la',
        'gc_phone_prefix' => '@856',
        'gc_name' => 'Laos',
        'gc_long_name' => "Lao People's Democratic Republic",
        'gc_continent' => 'AS',
        'gc_iso_3' => 'lao',
    ],
    'ls' => [
        'gc_id' => 'ls',
        'gc_phone_prefix' => '@266',
        'gc_name' => 'Lesotho',
        'gc_long_name' => 'Kingdom of Lesotho',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'lso',
    ],
    'lv' => [
        'gc_id' => 'lv',
        'gc_phone_prefix' => '@371',
        'gc_name' => 'Latvia',
        'gc_long_name' => 'Republic of Latvia',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'lva',
    ],
    'lb' => [
        'gc_id' => 'lb',
        'gc_phone_prefix' => '@961',
        'gc_name' => 'Lebanon',
        'gc_long_name' => 'Republic of Lebanon',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'lbn',
    ],
    'lr' => [
        'gc_id' => 'lr',
        'gc_phone_prefix' => '@231',
        'gc_name' => 'Liberia',
        'gc_long_name' => 'Republic of Liberia',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'lbr',
    ],
    'ly' => [
        'gc_id' => 'ly',
        'gc_phone_prefix' => '@218',
        'gc_name' => 'Libya',
        'gc_long_name' => "Socialist People's Libyan Arab Great Jamahiriya",
        'gc_continent' => 'AF',
        'gc_iso_3' => 'lby',
    ],
    'li' => [
        'gc_id' => 'li',
        'gc_phone_prefix' => '@410',
        'gc_name' => 'Liechtenstein',
        'gc_long_name' => 'Principality of Liechtenstein',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'lie',
    ],
    'lt' => [
        'gc_id' => 'lt',
        'gc_phone_prefix' => '@370',
        'gc_name' => 'Lithuania',
        'gc_long_name' => 'Republic of Lithuania',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'ltu',
    ],
    'lu' => [
        'gc_id' => 'lu',
        'gc_phone_prefix' => '@352',
        'gc_name' => 'Luxembourg',
        'gc_long_name' => 'Grand Duchy of Luxembourg',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'lux',
    ],
    'ch' => [
        'gc_id' => 'ch',
        'gc_phone_prefix' => '@041',
        'gc_name' => 'Switzerland',
        'gc_long_name' => 'Swiss Confederation',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'che',
    ],
    'mk' => [
        'gc_id' => 'mk',
        'gc_phone_prefix' => '@389',
        'gc_name' => 'Macedonia',
        'gc_long_name' => 'Republic of Macedonia',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'mkd',
    ],
    'mg' => [
        'gc_id' => 'mg',
        'gc_phone_prefix' => '@261',
        'gc_name' => 'Madagascar',
        'gc_long_name' => 'Republic of Madagascar',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'mdg',
    ],
    'my' => [
        'gc_id' => 'my',
        'gc_phone_prefix' => '@060',
        'gc_name' => 'Malaysia',
        'gc_long_name' => 'Malaysia',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'mys',
    ],
    'mw' => [
        'gc_id' => 'mw',
        'gc_phone_prefix' => '@265',
        'gc_name' => 'Malawi',
        'gc_long_name' => 'Republic of Malawi',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'mwi',
    ],
    'mv' => [
        'gc_id' => 'mv',
        'gc_phone_prefix' => '@960',
        'gc_name' => 'Maldives',
        'gc_long_name' => 'Republic of Maldives',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'mdv',
    ],
    'ml' => [
        'gc_id' => 'ml',
        'gc_phone_prefix' => '@223',
        'gc_name' => 'Mali',
        'gc_long_name' => 'Republic of Mali',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'mli',
    ],
    'mt' => [
        'gc_id' => 'mt',
        'gc_phone_prefix' => '@356',
        'gc_name' => 'Malta',
        'gc_long_name' => 'Republic of Malta',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'mlt',
    ],
    'sr' => [
        'gc_id' => 'sr',
        'gc_phone_prefix' => '@597',
        'gc_name' => 'Suriname',
        'gc_long_name' => 'Republic of Suriname',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'sur',
    ],
    'ma' => [
        'gc_id' => 'ma',
        'gc_phone_prefix' => '@212',
        'gc_name' => 'Morocco',
        'gc_long_name' => 'Kingdom fo Morocco',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'mar',
    ],
    'mh' => [
        'gc_id' => 'mh',
        'gc_phone_prefix' => '@692',
        'gc_name' => 'Marshall Islands',
        'gc_long_name' => 'Republic of the Marshall Islands',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'mhl',
    ],
    'mu' => [
        'gc_id' => 'mu',
        'gc_phone_prefix' => '@230',
        'gc_name' => 'Mauritius',
        'gc_long_name' => 'Republic of Mauritius',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'mus',
    ],
    'mr' => [
        'gc_id' => 'mr',
        'gc_phone_prefix' => '@222',
        'gc_name' => 'Mauritania',
        'gc_long_name' => 'Islamic Republic of Mauritania',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'mrt',
    ],
    'mx' => [
        'gc_id' => 'mx',
        'gc_phone_prefix' => '@052',
        'gc_name' => 'Mexico',
        'gc_long_name' => 'United Mexican States',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'mex',
    ],
    'fm' => [
        'gc_id' => 'fm',
        'gc_phone_prefix' => '@691',
        'gc_name' => 'Micronesia',
        'gc_long_name' => 'Federated States of Micronesia',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'fsm',
    ],
    'md' => [
        'gc_id' => 'md',
        'gc_phone_prefix' => '@037',
        'gc_name' => 'Moldova',
        'gc_long_name' => 'Republic of Moldova',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'mda',
    ],
    'mc' => [
        'gc_id' => 'mc',
        'gc_phone_prefix' => '@377',
        'gc_name' => 'Monaco',
        'gc_long_name' => 'Principality of Monaco',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'mco',
    ],
    'mn' => [
        'gc_id' => 'mn',
        'gc_phone_prefix' => '@976',
        'gc_name' => 'Mongolia',
        'gc_long_name' => 'Mongolia',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'mng',
    ],
    'mz' => [
        'gc_id' => 'mz',
        'gc_phone_prefix' => '@258',
        'gc_name' => 'Mozambique',
        'gc_long_name' => 'Republic of Mozambique',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'moz',
    ],
    'mm' => [
        'gc_id' => 'mm',
        'gc_phone_prefix' => '@095',
        'gc_name' => 'Burma',
        'gc_long_name' => 'Union of Myanmar',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'mmr',
    ],
    'na' => [
        'gc_id' => 'na',
        'gc_phone_prefix' => '@264',
        'gc_name' => 'Namibia',
        'gc_long_name' => 'Republic of Namibia',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'nam',
    ],
    'nr' => [
        'gc_id' => 'nr',
        'gc_phone_prefix' => '@674',
        'gc_name' => 'Nauru',
        'gc_long_name' => 'Republic of Nauru',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'nru',
    ],
    'np' => [
        'gc_id' => 'np',
        'gc_phone_prefix' => '@977',
        'gc_name' => 'Nepal',
        'gc_long_name' => 'Federated Democratic Republic of Nepal',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'npl',
    ],
    'ni' => [
        'gc_id' => 'ni',
        'gc_phone_prefix' => '@505',
        'gc_name' => 'Nicaragua',
        'gc_long_name' => 'Republic of Nicaragua',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'nic',
    ],
    'ne' => [
        'gc_id' => 'ne',
        'gc_phone_prefix' => '@227',
        'gc_name' => 'Niger',
        'gc_long_name' => 'Republic of Niger',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'ner',
    ],
    'ng' => [
        'gc_id' => 'ng',
        'gc_phone_prefix' => '@234',
        'gc_name' => 'Nigeria',
        'gc_long_name' => 'Federal Republic of Nigeria',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'nga',
    ],
    'no' => [
        'gc_id' => 'no',
        'gc_phone_prefix' => '@047',
        'gc_name' => 'Norway',
        'gc_long_name' => 'Kingdom of Norway',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'nor',
    ],
    'nz' => [
        'gc_id' => 'nz',
        'gc_phone_prefix' => '@064',
        'gc_name' => 'New Zealand',
        'gc_long_name' => 'New Zealand',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'nzl',
    ],
    'om' => [
        'gc_id' => 'om',
        'gc_phone_prefix' => '@968',
        'gc_name' => 'Oman',
        'gc_long_name' => 'Sultanate of Oman',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'omn',
    ],
    'ug' => [
        'gc_id' => 'ug',
        'gc_phone_prefix' => '@256',
        'gc_name' => 'Uganda',
        'gc_long_name' => 'Republic of Uganda',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'uga',
    ],
    'uz' => [
        'gc_id' => 'uz',
        'gc_phone_prefix' => '@071',
        'gc_name' => 'Uzbekistan',
        'gc_long_name' => 'Republic of Uzbekistan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'uzb',
    ],
    'pk' => [
        'gc_id' => 'pk',
        'gc_phone_prefix' => '@092',
        'gc_name' => 'Pakistan',
        'gc_long_name' => 'Islamic Republic of Pakistan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'pak',
    ],
    'pw' => [
        'gc_id' => 'pw',
        'gc_phone_prefix' => '@680',
        'gc_name' => 'Palau',
        'gc_long_name' => 'Republic of Palau',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'plw',
    ],
    'ps' => [
        'gc_id' => 'ps',
        'gc_phone_prefix' => '@970',
        'gc_name' => 'Palestine',
        'gc_long_name' => 'State of Palestine',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'pse',
    ],
    'pa' => [
        'gc_id' => 'pa',
        'gc_phone_prefix' => '@507',
        'gc_name' => 'Panama',
        'gc_long_name' => 'Republic of Panama',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'pan',
    ],
    'pg' => [
        'gc_id' => 'pg',
        'gc_phone_prefix' => '@675',
        'gc_name' => 'Papua New Guinea',
        'gc_long_name' => 'Independent State of Papua New Guinea',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'png',
    ],
    'py' => [
        'gc_id' => 'py',
        'gc_phone_prefix' => '@595',
        'gc_name' => 'Paraguay',
        'gc_long_name' => 'Republic of Paraguay',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'pry',
    ],
    'nl' => [
        'gc_id' => 'nl',
        'gc_phone_prefix' => '@031',
        'gc_name' => 'Netherlands',
        'gc_long_name' => 'Kingdom of the Netherlands',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'nld',
    ],
    'ph' => [
        'gc_id' => 'ph',
        'gc_phone_prefix' => '@063',
        'gc_name' => 'Philippines',
        'gc_long_name' => 'Republic of the Philippines',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'phl',
    ],
    'pl' => [
        'gc_id' => 'pl',
        'gc_phone_prefix' => '@048',
        'gc_name' => 'Poland',
        'gc_long_name' => 'Republic of Poland',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'pol',
    ],
    'pt' => [
        'gc_id' => 'pt',
        'gc_phone_prefix' => '@351',
        'gc_name' => 'Portugal',
        'gc_long_name' => 'Portuguese Republic',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'prt',
    ],
    'qa' => [
        'gc_id' => 'qa',
        'gc_phone_prefix' => '@974',
        'gc_name' => 'Qatar',
        'gc_long_name' => 'State of Qatar',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'qat',
    ],
    'ro' => [
        'gc_id' => 'ro',
        'gc_phone_prefix' => '@040',
        'gc_name' => 'Romania',
        'gc_long_name' => 'Romania',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'rom',
    ],
    'gb' => [
        'gc_id' => 'gb',
        'gc_phone_prefix' => '@044',
        'gc_name' => 'United Kingdom',
        'gc_long_name' => 'United Kingdom of Great Britain and Northern Ireland',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'gbr',
    ],
    'ru' => [
        'gc_id' => 'ru',
        'gc_phone_prefix' => '@007',
        'gc_name' => 'Russia',
        'gc_long_name' => 'Russian Federation',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'rus',
    ],
    'rw' => [
        'gc_id' => 'rw',
        'gc_phone_prefix' => '@250',
        'gc_name' => 'Rwanda',
        'gc_long_name' => 'Republic of Rwanda',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'rwa',
    ],
    'vc' => [
        'gc_id' => 'vc',
        'gc_phone_prefix' => '@818',
        'gc_name' => 'Saint Vincent and the Grenadines',
        'gc_long_name' => 'Saint Vincent and the Grenadines',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'vct',
    ],
    'kn' => [
        'gc_id' => 'kn',
        'gc_phone_prefix' => '@869',
        'gc_name' => 'Saint Kitts and Nevis',
        'gc_long_name' => 'Saint Kitts and Nevis',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'kna',
    ],
    'sm' => [
        'gc_id' => 'sm',
        'gc_phone_prefix' => '@378',
        'gc_name' => 'San Marino',
        'gc_long_name' => 'Republic of San Marino',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'smr',
    ],
    'va' => [
        'gc_id' => 'va',
        'gc_phone_prefix' => '@396',
        'gc_name' => 'Vatican City',
        'gc_long_name' => 'Holy See (Vatican City State)',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'vat',
    ],
    'lc' => [
        'gc_id' => 'lc',
        'gc_phone_prefix' => '@758',
        'gc_name' => 'Saint Lucia',
        'gc_long_name' => 'Saint Lucia',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'lca',
    ],
    'sb' => [
        'gc_id' => 'sb',
        'gc_phone_prefix' => '@677',
        'gc_name' => 'Solomon Islands',
        'gc_long_name' => 'Solomon Islands',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'slb',
    ],
    'sv' => [
        'gc_id' => 'sv',
        'gc_phone_prefix' => '@503',
        'gc_name' => 'El Salvador',
        'gc_long_name' => 'Republic of El Salvador',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'slv',
    ],
    'ws' => [
        'gc_id' => 'ws',
        'gc_phone_prefix' => '@685',
        'gc_name' => 'Samoa',
        'gc_long_name' => 'Independent State of Samoa',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'wsm',
    ],
    'pe' => [
        'gc_id' => 'pe',
        'gc_phone_prefix' => '@051',
        'gc_name' => 'Peru',
        'gc_long_name' => 'Republic of Peru',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'per',
    ],
    'sn' => [
        'gc_id' => 'sn',
        'gc_phone_prefix' => '@221',
        'gc_name' => 'Senegal',
        'gc_long_name' => 'Republic of Senegal',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'sen',
    ],
    'sz' => [
        'gc_id' => 'sz',
        'gc_phone_prefix' => '@268',
        'gc_name' => 'Swaziland',
        'gc_long_name' => 'Kingdom of Swaziland',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'swz',
    ],
    'sc' => [
        'gc_id' => 'sc',
        'gc_phone_prefix' => '@248',
        'gc_name' => 'Seychelles',
        'gc_long_name' => 'Republic of Seychelles',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'syc',
    ],
    'sl' => [
        'gc_id' => 'sl',
        'gc_phone_prefix' => '@232',
        'gc_name' => 'Sierra Leone',
        'gc_long_name' => 'Republic of Sierra Leone',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'sle',
    ],
    'sg' => [
        'gc_id' => 'sg',
        'gc_phone_prefix' => '@065',
        'gc_name' => 'Singapore',
        'gc_long_name' => 'Republic of Singapore',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'sgp',
    ],
    'sk' => [
        'gc_id' => 'sk',
        'gc_phone_prefix' => '@042',
        'gc_name' => 'Slovakia',
        'gc_long_name' => 'Slovak Republic',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'svk',
    ],
    'si' => [
        'gc_id' => 'si',
        'gc_phone_prefix' => '@386',
        'gc_name' => 'Slovenia',
        'gc_long_name' => 'Republic of Slovenia',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'svn',
    ],
    'so' => [
        'gc_id' => 'so',
        'gc_phone_prefix' => '@252',
        'gc_name' => 'Somalia',
        'gc_long_name' => 'Federal Republic of Somalia',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'som',
    ],
    'sd' => [
        'gc_id' => 'sd',
        'gc_phone_prefix' => '@249',
        'gc_name' => 'Sudan',
        'gc_long_name' => 'Republic of Sudan',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'sdn',
    ],
    'sy' => [
        'gc_id' => 'sy',
        'gc_phone_prefix' => '@963',
        'gc_name' => 'Syria',
        'gc_long_name' => 'Syrian Arab Republic',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'syr',
    ],
    'tj' => [
        'gc_id' => 'tj',
        'gc_phone_prefix' => '@072',
        'gc_name' => 'Tajikistan',
        'gc_long_name' => 'Republic of Tajikistan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'tjk',
    ],
    'tz' => [
        'gc_id' => 'tz',
        'gc_phone_prefix' => '@255',
        'gc_name' => 'Tanzania',
        'gc_long_name' => 'United Republic of Tanzania',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'tza',
    ],
    'td' => [
        'gc_id' => 'td',
        'gc_phone_prefix' => '@235',
        'gc_name' => 'Chad',
        'gc_long_name' => 'Republic of Chad',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'tcd',
    ],
    'cz' => [
        'gc_id' => 'cz',
        'gc_phone_prefix' => '@420',
        'gc_name' => 'Czech Republic',
        'gc_long_name' => 'Czech Republic',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'cze',
    ],
    'th' => [
        'gc_id' => 'th',
        'gc_phone_prefix' => '@066',
        'gc_name' => 'Thailand',
        'gc_long_name' => 'Kingdom of Thailand',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'tha',
    ],
    'tl' => [
        'gc_id' => 'tl',
        'gc_phone_prefix' => '@670',
        'gc_name' => 'East Timor',
        'gc_long_name' => 'Democratic Republic of Timor-Leste',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'tls',
    ],
    'tg' => [
        'gc_id' => 'tg',
        'gc_phone_prefix' => '@228',
        'gc_name' => 'Togo',
        'gc_long_name' => 'Togolese Republic',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'tgo',
    ],
    'to' => [
        'gc_id' => 'to',
        'gc_phone_prefix' => '@676',
        'gc_name' => 'Tonga',
        'gc_long_name' => 'Kingdom of Tonga',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'ton',
    ],
    'tt' => [
        'gc_id' => 'tt',
        'gc_phone_prefix' => '@868',
        'gc_name' => 'Trinidad and Tobago',
        'gc_long_name' => 'Republic of Trinidad and Tobago',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'tto',
    ],
    'tn' => [
        'gc_id' => 'tn',
        'gc_phone_prefix' => '@216',
        'gc_name' => 'Tunisia',
        'gc_long_name' => 'Republic of Tunisia',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'tun',
    ],
    'tm' => [
        'gc_id' => 'tm',
        'gc_phone_prefix' => '@993',
        'gc_name' => 'Turkmenistan',
        'gc_long_name' => 'Turkmenistan',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'tkm',
    ],
    'tr' => [
        'gc_id' => 'tr',
        'gc_phone_prefix' => '@090',
        'gc_name' => 'Turkey',
        'gc_long_name' => 'Republic of Turkey',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'tur',
    ],
    'tv' => [
        'gc_id' => 'tv',
        'gc_phone_prefix' => '@688',
        'gc_name' => 'Tuvalu',
        'gc_long_name' => 'Tuvalu',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'tuv',
    ],
    'ua' => [
        'gc_id' => 'ua',
        'gc_phone_prefix' => '@380',
        'gc_name' => 'Ukraine',
        'gc_long_name' => 'Ukraine',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'ukr',
    ],
    'uy' => [
        'gc_id' => 'uy',
        'gc_phone_prefix' => '@598',
        'gc_name' => 'Uruguay',
        'gc_long_name' => 'Eastern Republic of Uruguay',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'ury',
    ],
    'vu' => [
        'gc_id' => 'vu',
        'gc_phone_prefix' => '@678',
        'gc_name' => 'Vanuatu',
        'gc_long_name' => 'Republic of Vanuatu',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'vut',
    ],
    've' => [
        'gc_id' => 've',
        'gc_phone_prefix' => '@058',
        'gc_name' => 'Venezuela',
        'gc_long_name' => 'Bolivarian Republic of Venezuela',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'ven',
    ],
    'vn' => [
        'gc_id' => 'vn',
        'gc_phone_prefix' => '@084',
        'gc_name' => 'Vietnam',
        'gc_long_name' => 'Socialistic Republic of Vietnam',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'vnm',
    ],
    'ye' => [
        'gc_id' => 'ye',
        'gc_phone_prefix' => '@967',
        'gc_name' => 'Yemen',
        'gc_long_name' => 'Republic of Yemen',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'yem',
    ],
    'zm' => [
        'gc_id' => 'zm',
        'gc_phone_prefix' => '@260',
        'gc_name' => 'Zambia',
        'gc_long_name' => 'Republic of Zambia',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'zmb',
    ],
    'zw' => [
        'gc_id' => 'zw',
        'gc_phone_prefix' => '@263',
        'gc_name' => 'Zimbabwe',
        'gc_long_name' => 'Republic of Zimbabwe',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'zwe',
    ],
    'cn' => [
        'gc_id' => 'cn',
        'gc_phone_prefix' => '@086',
        'gc_name' => 'China',
        'gc_long_name' => "People's Republic of China",
        'gc_continent' => 'AS',
        'gc_iso_3' => 'chn',
    ],
    'mo' => [
        'gc_id' => 'mo',
        'gc_phone_prefix' => '@853',
        'gc_name' => 'Macau',
        'gc_long_name' => 'Macau',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'mac',
    ],
    'hk' => [
        'gc_id' => 'hk',
        'gc_phone_prefix' => '@852',
        'gc_name' => 'Hong Kong',
        'gc_long_name' => 'Hong Kong',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'hkg',
    ],
    'bm' => [
        'gc_id' => 'bm',
        'gc_phone_prefix' => '@441',
        'gc_name' => 'Bermuda',
        'gc_long_name' => 'Bermuda Islands',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'bmu',
    ],
    'gi' => [
        'gc_id' => 'gi',
        'gc_phone_prefix' => '@350',
        'gc_name' => 'Gibraltar',
        'gc_long_name' => 'Gibraltar',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'gib',
    ],
    'mp' => [
        'gc_id' => 'mp',
        'gc_phone_prefix' => '@1670',
        'gc_name' => 'Northern Mariana Islands',
        'gc_long_name' => 'Commonwealth of the Northern Mariana Islands',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'mnp',
    ],
    'ai' => [
        'gc_id' => 'ai',
        'gc_phone_prefix' => '@1264',
        'gc_name' => 'Anguilla',
        'gc_long_name' => 'Anguilla',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'aia',
    ],
    'an' => [
        'gc_id' => 'an',
        'gc_phone_prefix' => '@599',
        'gc_name' => 'Netherlands Antilles',
        'gc_long_name' => 'Netherlands Antilles',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'ant',
    ],
    'aq' => [
        'gc_id' => 'aq',
        'gc_phone_prefix' => '',
        'gc_name' => 'Antarctica',
        'gc_long_name' => 'Antarctica',
        'gc_continent' => 'AN',
        'gc_iso_3' => 'ata',
    ],
    'as' => [
        'gc_id' => 'as',
        'gc_phone_prefix' => '@1684',
        'gc_name' => 'American Samoa',
        'gc_long_name' => 'American Samoa',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'asm',
    ],
    'aw' => [
        'gc_id' => 'aw',
        'gc_phone_prefix' => '@297',
        'gc_name' => 'Aruba',
        'gc_long_name' => 'Aruba',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'abw',
    ],
    'cc' => [
        'gc_id' => 'cc',
        'gc_phone_prefix' => '@61891',
        'gc_name' => 'Cocos Islands',
        'gc_long_name' => 'Territory of Cocos (Keeling) Islands',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'cck',
    ],
    'ck' => [
        'gc_id' => 'ck',
        'gc_phone_prefix' => '@682',
        'gc_name' => 'Cook Islands',
        'gc_long_name' => 'Cook Islands',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'cok',
    ],
    'cx' => [
        'gc_id' => 'cx',
        'gc_phone_prefix' => '@61',
        'gc_name' => 'Christmas Island',
        'gc_long_name' => 'Christmas Island',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'cxr',
    ],
    'eh' => [
        'gc_id' => 'eh',
        'gc_phone_prefix' => '@212',
        'gc_name' => 'Western Sahara',
        'gc_long_name' => 'Western Sahara',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'esh',
    ],
    'fk' => [
        'gc_id' => 'fk',
        'gc_phone_prefix' => '@500',
        'gc_name' => 'Falkland Islands',
        'gc_long_name' => 'Falkland Islands',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'flk',
    ],
    'fo' => [
        'gc_id' => 'fo',
        'gc_phone_prefix' => '@298',
        'gc_name' => 'Faroe Islands',
        'gc_long_name' => 'Faroe Islands',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'fro',
    ],
    'gf' => [
        'gc_id' => 'gf',
        'gc_phone_prefix' => '',
        'gc_name' => 'French Guiana',
        'gc_long_name' => 'French Guiana',
        'gc_continent' => 'SA',
        'gc_iso_3' => 'guf',
    ],
    'gg' => [
        'gc_id' => 'gg',
        'gc_phone_prefix' => '@441481',
        'gc_name' => 'Guernsey',
        'gc_long_name' => 'Bailiwick of Guernsey',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'ggy',
    ],
    'gl' => [
        'gc_id' => 'gl',
        'gc_phone_prefix' => '@299',
        'gc_name' => 'Greenland',
        'gc_long_name' => 'Greenland',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'grl',
    ],
    'gp' => [
        'gc_id' => 'gp',
        'gc_phone_prefix' => '',
        'gc_name' => 'Guadeloupe',
        'gc_long_name' => 'Guadeloupe',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'glp',
    ],
    'gs' => [
        'gc_id' => 'gs',
        'gc_phone_prefix' => '',
        'gc_name' => 'South Georgia and the South Sandwich Islands',
        'gc_long_name' => 'South Georgia and the South Sandwich Islands',
        'gc_continent' => 'AN',
        'gc_iso_3' => 'sgs',
    ],
    'gu' => [
        'gc_id' => 'gu',
        'gc_phone_prefix' => '@1671',
        'gc_name' => 'Guam',
        'gc_long_name' => 'Guam',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'gum',
    ],
    'im' => [
        'gc_id' => 'im',
        'gc_phone_prefix' => '@4401624',
        'gc_name' => 'Isle of Man',
        'gc_long_name' => 'Isle of Man',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'imn',
    ],
    'io' => [
        'gc_id' => 'io',
        'gc_phone_prefix' => '@246',
        'gc_name' => 'British Indian Ocean Territory',
        'gc_long_name' => 'British Indian Ocean Territory',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'iot',
    ],
    'je' => [
        'gc_id' => 'je',
        'gc_phone_prefix' => '@441534',
        'gc_name' => 'Jersey',
        'gc_long_name' => 'Bailiwick of Jersey',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'jey',
    ],
    'ky' => [
        'gc_id' => 'ky',
        'gc_phone_prefix' => '@1345',
        'gc_name' => 'Cayman Islands',
        'gc_long_name' => 'Cayman Islands',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'cym',
    ],
    'mf' => [
        'gc_id' => 'mf',
        'gc_phone_prefix' => '',
        'gc_name' => 'Saint Martin',
        'gc_long_name' => 'Saint Martin',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'maf',
    ],
    'mq' => [
        'gc_id' => 'mq',
        'gc_phone_prefix' => '',
        'gc_name' => 'Martinique',
        'gc_long_name' => 'Martinique',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'mtq',
    ],
    'ms' => [
        'gc_id' => 'ms',
        'gc_phone_prefix' => '@1664',
        'gc_name' => 'Montserrat',
        'gc_long_name' => 'Montserrat',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'msr',
    ],
    'nc' => [
        'gc_id' => 'nc',
        'gc_phone_prefix' => '@687',
        'gc_name' => 'New Caledonia',
        'gc_long_name' => 'New Caledonia',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'ncl',
    ],
    'nf' => [
        'gc_id' => 'nf',
        'gc_phone_prefix' => '@6723',
        'gc_name' => 'Norfolk Island',
        'gc_long_name' => 'Norfolk Island',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'nfk',
    ],
    'nu' => [
        'gc_id' => 'nu',
        'gc_phone_prefix' => '@683',
        'gc_name' => 'Niue',
        'gc_long_name' => 'Niue',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'niu',
    ],
    'pf' => [
        'gc_id' => 'pf',
        'gc_phone_prefix' => '@689',
        'gc_name' => 'French Polynesia',
        'gc_long_name' => 'French Polynesia',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'pyf',
    ],
    'pm' => [
        'gc_id' => 'pm',
        'gc_phone_prefix' => '@508',
        'gc_name' => 'Saint Pierre and Miquelon',
        'gc_long_name' => 'Territorial Collectivity of Saint Pierre and Miquelon',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'spm',
    ],
    'pn' => [
        'gc_id' => 'pn',
        'gc_phone_prefix' => '@64',
        'gc_name' => 'Pitcairn',
        'gc_long_name' => 'Pitcairn Islands',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'pcn',
    ],
    'pr' => [
        'gc_id' => 'pr',
        'gc_phone_prefix' => '@1787',
        'gc_name' => 'Puerto Rico',
        'gc_long_name' => 'Commonwealth of Puerto Rico',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'pri',
    ],
    'sh' => [
        'gc_id' => 'sh',
        'gc_phone_prefix' => '@290',
        'gc_name' => 'Saint Helena',
        'gc_long_name' => 'Saint Helena',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'shn',
    ],
    'tc' => [
        'gc_id' => 'tc',
        'gc_phone_prefix' => '@1649',
        'gc_name' => 'Turks and Caicos Islands',
        'gc_long_name' => 'Turks and Caicos Islands',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'tca',
    ],
    'tf' => [
        'gc_id' => 'tf',
        'gc_phone_prefix' => '',
        'gc_name' => 'French Southern Territories',
        'gc_long_name' => 'French Southern and Antarctic Lands',
        'gc_continent' => 'AN',
        'gc_iso_3' => 'atf',
    ],
    'tk' => [
        'gc_id' => 'tk',
        'gc_phone_prefix' => '@690',
        'gc_name' => 'Tokelau',
        'gc_long_name' => 'Tokelau',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'tkl',
    ],
    'tw' => [
        'gc_id' => 'tw',
        'gc_phone_prefix' => '@886',
        'gc_name' => 'Taiwan',
        'gc_long_name' => 'Republic of China',
        'gc_continent' => 'AS',
        'gc_iso_3' => 'twn',
    ],
    'um' => [
        'gc_id' => 'um',
        'gc_phone_prefix' => '',
        'gc_name' => 'United States Minor Outlying Islands',
        'gc_long_name' => 'United States Minor Outlying Islands',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'umi',
    ],
    'vg' => [
        'gc_id' => 'vg',
        'gc_phone_prefix' => '@1284',
        'gc_name' => 'British Virgin Islands',
        'gc_long_name' => 'British Virgin Islands',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'vgb',
    ],
    'vi' => [
        'gc_id' => 'vi',
        'gc_phone_prefix' => '@1340',
        'gc_name' => 'U.S. Virgin Islands',
        'gc_long_name' => 'United States Virgin Islands',
        'gc_continent' => 'NA',
        'gc_iso_3' => 'vir',
    ],
    'wf' => [
        'gc_id' => 'wf',
        'gc_phone_prefix' => '@681',
        'gc_name' => 'Wallis and Futuna',
        'gc_long_name' => 'Territory of the Wallis and Futuna',
        'gc_continent' => 'OC',
        'gc_iso_3' => 'wlf',
    ],
    'ww' => [
        'gc_id' => 'ww',
        'gc_phone_prefix' => '@',
        'gc_name' => 'World',
        'gc_long_name' => 'World',
        'gc_continent' => 'WW',
        'gc_iso_3' => 'www',
    ],
    'yt' => [
        'gc_id' => 'yt',
        'gc_phone_prefix' => '@262',
        'gc_name' => 'Mayotte',
        'gc_long_name' => 'Departmental Collectivity of Mayotte',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'myt',
    ],
    're' => [
        'gc_id' => 're',
        'gc_phone_prefix' => '',
        'gc_name' => 'Reunion',
        'gc_long_name' => 'Réunion',
        'gc_continent' => 'AF',
        'gc_iso_3' => 'reu',
    ],
    'ax' => [
        'gc_id' => 'ax',
        'gc_phone_prefix' => null,
        'gc_name' => 'ALAND ISLANDS',
        'gc_long_name' => 'ALAND ISLANDS',
        'gc_continent' => '??',
        'gc_iso_3' => 'ala',
    ],
    'asc' => [
        'gc_id' => 'asc',
        'gc_phone_prefix' => null,
        'gc_name' => 'ASCENSION ISLAND',
        'gc_long_name' => 'ASCENSION ISLAND',
        'gc_continent' => '??',
        'gc_iso_3' => 'asc',
    ],
    'bv' => [
        'gc_id' => 'bv',
        'gc_phone_prefix' => null,
        'gc_name' => 'BOUVET ISLAND',
        'gc_long_name' => 'BOUVET ISLAND',
        'gc_continent' => '??',
        'gc_iso_3' => 'bvt',
    ],
    'bum' => [
        'gc_id' => 'bumm',
        'gc_phone_prefix' => null,
        'gc_name' => 'BURMA',
        'gc_long_name' => 'BURMA',
        'gc_continent' => '??',
        'gc_iso_3' => 'xbu',
    ],
    'xic' => [
        'gc_id' => 'xic',
        'gc_phone_prefix' => null,
        'gc_name' => 'CANARY ISLANDS',
        'gc_long_name' => 'CANARY ISLANDS',
        'gc_continent' => '??',
        'gc_iso_3' => 'xic',
    ],
    'xea' => [
        'gc_id' => 'xea',
        'gc_phone_prefix' => null,
        'gc_name' => 'CEUTA, MELILLA',
        'gc_long_name' => 'CEUTA, MELILLA',
        'gc_continent' => '??',
        'gc_iso_3' => 'xea',
    ],
    'cpt' => [
        'gc_id' => 'cpt',
        'gc_phone_prefix' => null,
        'gc_name' => 'CLIPPERTON ISLAND',
        'gc_long_name' => 'CLIPPERTON ISLAND',
        'gc_continent' => '??',
        'gc_iso_3' => 'cpt',
    ],
    'dga' => [
        'gc_id' => 'dga',
        'gc_phone_prefix' => null,
        'gc_name' => 'DIEGO GARCIA',
        'gc_long_name' => 'DIEGO GARCIA',
        'gc_continent' => '??',
        'gc_iso_3' => 'dga',
    ],
    'tpt' => [
        'gc_id' => 'tptl',
        'gc_phone_prefix' => null,
        'gc_name' => 'EAST TIMOR',
        'gc_long_name' => 'EAST TIMOR',
        'gc_continent' => '??',
        'gc_iso_3' => 'xtl',
    ],
    'xtp' => [
        'gc_id' => 'xtp',
        'gc_phone_prefix' => null,
        'gc_name' => 'EAST TIMOR (TIMOR PORTUGUESE)',
        'gc_long_name' => 'EAST TIMOR (TIMOR PORTUGUESE)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xtp',
    ],
    'fxx' => [
        'gc_id' => 'fxx',
        'gc_phone_prefix' => null,
        'gc_name' => 'FRANCE, METROPOLITAN',
        'gc_long_name' => 'FRANCE, METROPOLITAN',
        'gc_continent' => '??',
        'gc_iso_3' => 'fxx',
    ],
    'hm' => [
        'gc_id' => 'hm',
        'gc_phone_prefix' => null,
        'gc_name' => 'HEARD ISLAND AND MCDONALD ISLANDS',
        'gc_long_name' => 'HEARD ISLAND AND MCDONALD ISLANDS',
        'gc_continent' => '??',
        'gc_iso_3' => 'hmd',
    ],
    'xlf' => [
        'gc_id' => 'xlf',
        'gc_phone_prefix' => null,
        'gc_name' => 'LIBYA FEZZAN',
        'gc_long_name' => 'LIBYA FEZZAN',
        'gc_continent' => '??',
        'gc_iso_3' => 'xlf',
    ],
    'anh' => [
        'gc_id' => 'anhh',
        'gc_phone_prefix' => null,
        'gc_name' => 'NETHERLANDS ANTILLES',
        'gc_long_name' => 'NETHERLANDS ANTILLES',
        'gc_continent' => '??',
        'gc_iso_3' => 'xan',
    ],
    'nth' => [
        'gc_id' => 'nthh',
        'gc_phone_prefix' => null,
        'gc_name' => 'NEUTRAL ZONE',
        'gc_long_name' => 'NEUTRAL ZONE',
        'gc_continent' => '??',
        'gc_iso_3' => 'xnt',
    ],
    'xsi' => [
        'gc_id' => 'xsi',
        'gc_phone_prefix' => null,
        'gc_name' => 'NEUTRAL ZONE BETWEEN SAUDI ARABIA (SA) AND IRAQ (IQ)',
        'gc_long_name' => 'NEUTRAL ZONE BETWEEN SAUDI ARABIA (SA) AND IRAQ (IQ)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xsi',
    ],
    'xps' => [
        'gc_id' => 'xps',
        'gc_phone_prefix' => null,
        'gc_name' => 'PALESTINIAN TERRITORY, OCCUPIED',
        'gc_long_name' => 'PALESTINIAN TERRITORY, OCCUPIED',
        'gc_continent' => '??',
        'gc_iso_3' => 'xps',
    ],
    'xsx' => [
        'gc_id' => 'xsx',
        'gc_phone_prefix' => null,
        'gc_name' => 'SAINT MARTIN',
        'gc_long_name' => 'SAINT MARTIN',
        'gc_continent' => '??',
        'gc_iso_3' => 'xsx',
    ],
    'xwv' => [
        'gc_id' => 'xwv',
        'gc_phone_prefix' => null,
        'gc_name' => 'SAINT VINCENT',
        'gc_long_name' => 'SAINT VINCENT',
        'gc_continent' => '??',
        'gc_iso_3' => 'xwv',
    ],
    'csx' => [
        'gc_id' => 'csxx',
        'gc_phone_prefix' => null,
        'gc_name' => 'SERBIA AND MONTENEGRO',
        'gc_long_name' => 'SERBIA AND MONTENEGRO',
        'gc_continent' => '??',
        'gc_iso_3' => 'xrm',
    ],
    'sj' => [
        'gc_id' => 'sj',
        'gc_phone_prefix' => null,
        'gc_name' => 'SVALBARD AND JAN MAYEN',
        'gc_long_name' => 'SVALBARD AND JAN MAYEN',
        'gc_continent' => '??',
        'gc_iso_3' => 'sjm',
    ],
    'taa' => [
        'gc_id' => 'taa',
        'gc_phone_prefix' => null,
        'gc_name' => 'TRISTAN DA CUNHA',
        'gc_long_name' => 'TRISTAN DA CUNHA',
        'gc_continent' => '??',
        'gc_iso_3' => 'taa',
    ],
    'suh' => [
        'gc_id' => 'suhh',
        'gc_phone_prefix' => null,
        'gc_name' => 'USSR',
        'gc_long_name' => 'USSR',
        'gc_continent' => '??',
        'gc_iso_3' => 'xsu',
    ],
    'yuc' => [
        'gc_id' => 'yucs',
        'gc_phone_prefix' => null,
        'gc_name' => 'YUGOSLAVIA',
        'gc_long_name' => 'YUGOSLAVIA',
        'gc_continent' => '??',
        'gc_iso_3' => 'xyu',
    ],
    'zrc' => [
        'gc_id' => 'zrcd',
        'gc_phone_prefix' => null,
        'gc_name' => 'ZAIRE',
        'gc_long_name' => 'ZAIRE',
        'gc_continent' => '??',
        'gc_iso_3' => 'xzr',
    ],
    'zz' => [
        'gc_id' => 'zz',
        'gc_phone_prefix' => null,
        'gc_name' => 'UNKNOWN',
        'gc_long_name' => 'UNKNOWN',
        'gc_continent' => '??',
        'gc_iso_3' => 'zzz',
    ],
    'xxa' => [
        'gc_id' => 'xxa',
        'gc_phone_prefix' => null,
        'gc_name' => 'STATELESS (1954 CONVENTION)',
        'gc_long_name' => 'STATELESS (1954 CONVENTION)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xxa',
    ],
    'aab' => [
        'gc_id' => 'aab',
        'gc_phone_prefix' => null,
        'gc_name' => 'BOPHUTHATSWANA',
        'gc_long_name' => 'BOPHUTHATSWANA',
        'gc_continent' => '??',
        'gc_iso_3' => 'aab',
    ],
    'bqa' => [
        'gc_id' => 'bqaq',
        'gc_phone_prefix' => null,
        'gc_name' => 'BRITISH ANTARCTIC TERRITORY',
        'gc_long_name' => 'BRITISH ANTARCTIC TERRITORY',
        'gc_continent' => '??',
        'gc_iso_3' => 'xbq',
    ],
    'ctk' => [
        'gc_id' => 'ctki',
        'gc_phone_prefix' => null,
        'gc_name' => 'CANTON AND ENDERBURY ISLANDS',
        'gc_long_name' => 'CANTON AND ENDERBURY ISLANDS',
        'gc_continent' => '??',
        'gc_iso_3' => 'xct',
    ],
    'aac' => [
        'gc_id' => 'aac',
        'gc_phone_prefix' => null,
        'gc_name' => 'CISKEI',
        'gc_long_name' => 'CISKEI',
        'gc_continent' => '??',
        'gc_iso_3' => 'aac',
    ],
    'csh' => [
        'gc_id' => 'cshh',
        'gc_phone_prefix' => null,
        'gc_name' => 'CZECHOSLOVAKIA',
        'gc_long_name' => 'CZECHOSLOVAKIA',
        'gc_continent' => '??',
        'gc_iso_3' => 'xcs',
    ],
    'dyb' => [
        'gc_id' => 'dybj',
        'gc_phone_prefix' => null,
        'gc_name' => 'DAHOMEY',
        'gc_long_name' => 'DAHOMEY',
        'gc_continent' => '??',
        'gc_iso_3' => 'xdy',
    ],
    'vdv' => [
        'gc_id' => 'vdvn',
        'gc_phone_prefix' => null,
        'gc_name' => 'VIET-NAM, DEMOCRATIC REPUBLIC OF (NORTH VIETNAM)',
        'gc_long_name' => 'VIET-NAM, DEMOCRATIC REPUBLIC OF (NORTH VIETNAM)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xvd',
    ],
    'ddd' => [
        'gc_id' => 'ddde',
        'gc_phone_prefix' => null,
        'gc_name' => 'GERMAN DEMOCRATIC REPUBLIC',
        'gc_long_name' => 'GERMAN DEMOCRATIC REPUBLIC',
        'gc_continent' => '??',
        'gc_iso_3' => 'xde',
    ],
    'fqh' => [
        'gc_id' => 'fqhh',
        'gc_phone_prefix' => null,
        'gc_name' => 'FRENCH SOUTHERN AND ANTARCTIC TERRITORIES',
        'gc_long_name' => 'FRENCH SOUTHERN AND ANTARCTIC TERRITORIES',
        'gc_continent' => '??',
        'gc_iso_3' => 'xfq',
    ],
    'aid' => [
        'gc_id' => 'aidj',
        'gc_phone_prefix' => null,
        'gc_name' => 'FRENCH TERRITORY OF THE AFARS AND THE ISSAS',
        'gc_long_name' => 'FRENCH TERRITORY OF THE AFARS AND THE ISSAS',
        'gc_continent' => '??',
        'gc_iso_3' => 'xai',
    ],
    'geh' => [
        'gc_id' => 'gehh',
        'gc_phone_prefix' => null,
        'gc_name' => 'GILBERT AND ELLIS ISLANDS',
        'gc_long_name' => 'GILBERT AND ELLIS ISLANDS',
        'gc_continent' => '??',
        'gc_iso_3' => 'xge',
    ],
    'jtu' => [
        'gc_id' => 'jtum',
        'gc_phone_prefix' => null,
        'gc_name' => 'JOHNSTON ISLAND',
        'gc_long_name' => 'JOHNSTON ISLAND',
        'gc_continent' => '??',
        'gc_iso_3' => 'xjt',
    ],
    'miu' => [
        'gc_id' => 'mium',
        'gc_phone_prefix' => null,
        'gc_name' => 'MIDWAY ISLANDS',
        'gc_long_name' => 'MIDWAY ISLANDS',
        'gc_continent' => '??',
        'gc_iso_3' => 'xmi',
    ],
    'nhv' => [
        'gc_id' => 'nhvu',
        'gc_phone_prefix' => null,
        'gc_name' => 'NEW HEBRIDES',
        'gc_long_name' => 'NEW HEBRIDES',
        'gc_continent' => '??',
        'gc_iso_3' => 'xnh',
    ],
    'pzp' => [
        'gc_id' => 'pzpa',
        'gc_phone_prefix' => null,
        'gc_name' => 'PANAMA CANAL ZONE',
        'gc_long_name' => 'PANAMA CANAL ZONE',
        'gc_continent' => '??',
        'gc_iso_3' => 'xpz',
    ],
    'xxx' => [
        'gc_id' => 'xxx',
        'gc_phone_prefix' => null,
        'gc_name' => 'UNSPECIFIED',
        'gc_long_name' => 'UNSPECIFIED',
        'gc_continent' => '??',
        'gc_iso_3' => 'xxx',
    ],
    'rhz' => [
        'gc_id' => 'rhzw',
        'gc_phone_prefix' => null,
        'gc_name' => 'RHODESIA',
        'gc_long_name' => 'RHODESIA',
        'gc_continent' => '??',
        'gc_iso_3' => 'xrh',
    ],
    'ski' => [
        'gc_id' => 'skin',
        'gc_phone_prefix' => null,
        'gc_name' => 'SIKKIM',
        'gc_long_name' => 'SIKKIM',
        'gc_continent' => '??',
        'gc_iso_3' => 'xsk',
    ],
    'pch' => [
        'gc_id' => 'pchh',
        'gc_phone_prefix' => null,
        'gc_name' => 'PACIFIC ISLANDS, TRUST TERRITORY OF THE',
        'gc_long_name' => 'PACIFIC ISLANDS, TRUST TERRITORY OF THE',
        'gc_continent' => '??',
        'gc_iso_3' => 'xpc',
    ],
    'aak' => [
        'gc_id' => 'aak',
        'gc_phone_prefix' => null,
        'gc_name' => 'RESIDENT OF KOSOVO (UNMIK)',
        'gc_long_name' => 'RESIDENT OF KOSOVO (UNMIK)',
        'gc_continent' => '??',
        'gc_iso_3' => 'aak',
    ],
    'puu' => [
        'gc_id' => 'puum',
        'gc_phone_prefix' => null,
        'gc_name' => 'U.S. MISCELLANEOUS PACIFIC ISLANDS',
        'gc_long_name' => 'U.S. MISCELLANEOUS PACIFIC ISLANDS',
        'gc_continent' => '??',
        'gc_iso_3' => 'xpu',
    ],
    'hvb' => [
        'gc_id' => 'hvbf',
        'gc_phone_prefix' => null,
        'gc_name' => 'UPPER VOLTA (HAUTE-VOLTA)',
        'gc_long_name' => 'UPPER VOLTA (HAUTE-VOLTA)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xhv',
    ],
    'aav' => [
        'gc_id' => 'aav',
        'gc_phone_prefix' => null,
        'gc_name' => 'VENDA',
        'gc_long_name' => 'VENDA',
        'gc_continent' => '??',
        'gc_iso_3' => 'aav',
    ],
    'wku' => [
        'gc_id' => 'wkum',
        'gc_phone_prefix' => null,
        'gc_name' => 'WAKE ISLAND',
        'gc_long_name' => 'WAKE ISLAND',
        'gc_continent' => '??',
        'gc_iso_3' => 'xwk',
    ],
    'nqa' => [
        'gc_id' => 'nqaq',
        'gc_phone_prefix' => null,
        'gc_name' => 'DRONNING MAUD LAND',
        'gc_long_name' => 'DRONNING MAUD LAND',
        'gc_continent' => '??',
        'gc_iso_3' => 'xnq',
    ],
    'aae' => [
        'gc_id' => 'aae',
        'gc_phone_prefix' => null,
        'gc_name' => 'ETHIOPIA (BEFORE ERITREA BROKE AWAY)',
        'gc_long_name' => 'ETHIOPIA (BEFORE ERITREA BROKE AWAY)',
        'gc_continent' => '??',
        'gc_iso_3' => 'aae',
    ],
    'aag' => [
        'gc_id' => 'aag',
        'gc_phone_prefix' => null,
        'gc_name' => 'GERMANY, FEDERAL REPUBLIC OF (WEST GERMANY)',
        'gc_long_name' => 'GERMANY, FEDERAL REPUBLIC OF (WEST GERMANY)',
        'gc_continent' => '??',
        'gc_iso_3' => 'aag',
    ],
    'aaa' => [
        'gc_id' => 'aaa',
        'gc_phone_prefix' => null,
        'gc_name' => 'NETHERLANDS ANTILLES (BEFORE ARUBA BROKE AWAY)',
        'gc_long_name' => 'NETHERLANDS ANTILLES (BEFORE ARUBA BROKE AWAY)',
        'gc_continent' => '??',
        'gc_iso_3' => 'aaa',
    ],
    'aap' => [
        'gc_id' => 'aap',
        'gc_phone_prefix' => null,
        'gc_name' => 'PANAMA (BEFORE MERGING WITH PANAMA CANAL ZONE)',
        'gc_long_name' => 'PANAMA (BEFORE MERGING WITH PANAMA CANAL ZONE)',
        'gc_continent' => '??',
        'gc_iso_3' => 'aap',
    ],
    'aas' => [
        'gc_id' => 'aas',
        'gc_phone_prefix' => null,
        'gc_name' => 'SAINT KITTS-NEVIS-ANGUILLA',
        'gc_long_name' => 'SAINT KITTS-NEVIS-ANGUILLA',
        'gc_continent' => '??',
        'gc_iso_3' => 'aas',
    ],
    'ydy' => [
        'gc_id' => 'ydye',
        'gc_phone_prefix' => null,
        'gc_name' => 'YEMEN, DEMOCRATIC (SOUTH YEMEN)',
        'gc_long_name' => 'YEMEN, DEMOCRATIC (SOUTH YEMEN)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xye',
    ],
    'aay' => [
        'gc_id' => 'aay',
        'gc_phone_prefix' => null,
        'gc_name' => 'YEMEN ARAB REPUBLIC (NORTH YEMEN)',
        'gc_long_name' => 'YEMEN ARAB REPUBLIC (NORTH YEMEN)',
        'gc_continent' => '??',
        'gc_iso_3' => 'aay',
    ],
    'xyr' => [
        'gc_id' => 'xyr',
        'gc_phone_prefix' => null,
        'gc_name' => 'SERBIA AND MONTENEGRO (YUGOSLAVIA, FEDERAL REPUBLIC OF)',
        'gc_long_name' => 'SERBIA AND MONTENEGRO (YUGOSLAVIA, FEDERAL REPUBLIC OF)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xyr',
    ],
    'xsv' => [
        'gc_id' => 'xsv',
        'gc_phone_prefix' => null,
        'gc_name' => 'VIET-NAM, REPUBLIC OF (SOUTH VIETNAM)',
        'gc_long_name' => 'VIET-NAM, REPUBLIC OF (SOUTH VIETNAM)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xsv',
    ],
    'xxb' => [
        'gc_id' => 'xxb',
        'gc_phone_prefix' => null,
        'gc_name' => 'REFUGEE (1951 CONVENTION)',
        'gc_long_name' => 'REFUGEE (1951 CONVENTION)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xxb',
    ],
    'xxc' => [
        'gc_id' => 'xxc',
        'gc_phone_prefix' => null,
        'gc_name' => 'REFUGEE (OTHER)',
        'gc_long_name' => 'REFUGEE (OTHER)',
        'gc_continent' => '??',
        'gc_iso_3' => 'xxc',
    ],
    'xuk' => [
        'gc_id' => 'xuk',
        'gc_phone_prefix' => null,
        'gc_name' => 'British Citizen',
        'gc_long_name' => 'British Citizen',
        'gc_continent' => '??',
        'gc_iso_3' => 'xuk',
    ],
    'gbd' => [
        'gc_id' => 'gbd',
        'gc_phone_prefix' => null,
        'gc_name' => 'British Dependent territories citizen',
        'gc_long_name' => 'British Dependent territories citizen',
        'gc_continent' => '??',
        'gc_iso_3' => 'gbd',
    ],
    'gbn' => [
        'gc_id' => 'gbn',
        'gc_phone_prefix' => null,
        'gc_name' => 'British National (Overseas)',
        'gc_long_name' => 'British National (Overseas)',
        'gc_continent' => '??',
        'gc_iso_3' => 'gbn',
    ],
    'gbo' => [
        'gc_id' => 'gbo',
        'gc_phone_prefix' => null,
        'gc_name' => 'British Overseas citizen',
        'gc_long_name' => 'British Overseas citizen',
        'gc_continent' => '??',
        'gc_iso_3' => 'gbo',
    ],
    'gbp' => [
        'gc_id' => 'gbp',
        'gc_phone_prefix' => null,
        'gc_name' => 'British Protected person',
        'gc_long_name' => 'British Protected person',
        'gc_continent' => '??',
        'gc_iso_3' => 'gbp',
    ],
    'gbs' => [
        'gc_id' => 'gbs',
        'gc_phone_prefix' => null,
        'gc_name' => 'British Subject',
        'gc_long_name' => 'British Subject',
        'gc_continent' => '??',
        'gc_iso_3' => 'gbs',
    ],
    'bq' => [
        'gc_id' => 'bq',
        'gc_phone_prefix' => null,
        'gc_name' => 'BONAIRE, SAINT EUSTATIUS AND SABA',
        'gc_long_name' => 'BONAIRE, SAINT EUSTATIUS AND SABA',
        'gc_continent' => '??',
        'gc_iso_3' => 'bes',
    ],
    'cw' => [
        'gc_id' => 'cw',
        'gc_phone_prefix' => null,
        'gc_name' => 'CURAÇAO',
        'gc_long_name' => 'CURAÇAO',
        'gc_continent' => '??',
        'gc_iso_3' => 'cuw',
    ],
    'sx' => [
        'gc_id' => 'sx',
        'gc_phone_prefix' => null,
        'gc_name' => 'SINT MAARTEN (DUTCH PART)',
        'gc_long_name' => 'SINT MAARTEN (DUTCH PART)',
        'gc_continent' => '??',
        'gc_iso_3' => 'sxm',
    ],
    'xb' => [
        'gc_id' => 'xb',
        'gc_phone_prefix' => null,
        'gc_name' => 'Palestinian nationality not recognized by all States',
        'gc_long_name' => 'Palestinian nationality not recognized by all States',
        'gc_continent' => '??',
        'gc_iso_3' => 'qps',
    ],
    'ss' => [
        'gc_id' => 'ss',
        'gc_phone_prefix' => null,
        'gc_name' => 'South Sudan',
        'gc_long_name' => 'South Sudan',
        'gc_continent' => '??',
        'gc_iso_3' => 'ssd',
    ],
    'xk' => [
        'gc_id' => 'xk',
        'gc_phone_prefix' => '@381',
        'gc_name' => 'Kosovo',
        'gc_long_name' => 'Republic of Kosovo',
        'gc_continent' => 'EU',
        'gc_iso_3' => 'unk',
    ],
];
