apiVersion: v1
kind: Template
metadata:
  name: payment-api-cronjob-template
  annotations:
    description: This template defines objects that are required to spin up a TLS Connect cronjob
parameters:
  - name: JOB_NAME
    description: Name of the job
    required: true
    displayName: Application Name
  - name: APPLICATION_NAME
    description: Name of the application
    required: true
    displayName: Application Name
  - name: SCHEDULE
    required: true
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}-${JOB_NAME}
    spec:
      schedule: "${SCHEDULE}"
      jobTemplate:
        spec:
          template:
            metadata:
              annotations:
                central-logging: "true"
            spec:
              containers:
                - name: remote-exec
                  image: docker-registry.tlscontact.com/openshift/origin-cli:v3.11
                  command: ['/bin/bash','-c']
                  args:
                    - POD=`oc get pods -o jsonpath='{.items[0].metadata.name}' --selector deploymentconfig=${APPLICATION_NAME}`;
                      echo 'Found POD $POD';
                      oc exec $POD -- bash -c "ls -la; php ./artisan schedule:run"
              serviceAccountName: php-cron-sa
              restartPolicy: Never
